// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

/**
 * Protobuf type {@code BondCoupons}
 */
public  final class BondCoupons extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BondCoupons)
    BondCouponsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BondCoupons.newBuilder() to construct.
  private BondCoupons(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BondCoupons() {
    beginPeriod_ = "";
    endPeriod_ = "";
    stopTradeDate_ = "";
    payDate_ = "";
    couponRateDate_ = "";
    fixDate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BondCoupons();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BondCoupons(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            idFintool_ = input.readInt64();
            break;
          }
          case 16: {

            idCoupon_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            beginPeriod_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            endPeriod_ = s;
            break;
          }
          case 40: {

            couponPeriod_ = input.readInt64();
            break;
          }
          case 48: {

            daysFromDist_ = input.readInt64();
            break;
          }
          case 58: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (couponRate_ != null) {
              subBuilder = couponRate_.toBuilder();
            }
            couponRate_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(couponRate_);
              couponRate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (payPerBound_ != null) {
              subBuilder = payPerBound_.toBuilder();
            }
            payPerBound_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(payPerBound_);
              payPerBound_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (couponVal_ != null) {
              subBuilder = couponVal_.toBuilder();
            }
            couponVal_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(couponVal_);
              couponVal_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            stopTradeDate_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            payDate_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            couponRateDate_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            fixDate_ = s;
            break;
          }
          case 112: {

            updateDate_ = input.readInt64();
            break;
          }
          case 122: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (payPerBondFrac_ != null) {
              subBuilder = payPerBondFrac_.toBuilder();
            }
            payPerBondFrac_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(payPerBondFrac_);
              payPerBondFrac_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondCoupons_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondCoupons_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons.Builder.class);
  }

  public static final int ID_FINTOOL_FIELD_NUMBER = 1;
  private long idFintool_;
  /**
   * <code>int64 id_fintool = 1;</code>
   */
  public long getIdFintool() {
    return idFintool_;
  }

  public static final int ID_COUPON_FIELD_NUMBER = 2;
  private long idCoupon_;
  /**
   * <code>int64 id_coupon = 2;</code>
   */
  public long getIdCoupon() {
    return idCoupon_;
  }

  public static final int BEGIN_PERIOD_FIELD_NUMBER = 3;
  private volatile java.lang.Object beginPeriod_;
  /**
   * <code>string begin_period = 3;</code>
   */
  public java.lang.String getBeginPeriod() {
    java.lang.Object ref = beginPeriod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      beginPeriod_ = s;
      return s;
    }
  }
  /**
   * <code>string begin_period = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBeginPeriodBytes() {
    java.lang.Object ref = beginPeriod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      beginPeriod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int END_PERIOD_FIELD_NUMBER = 4;
  private volatile java.lang.Object endPeriod_;
  /**
   * <code>string end_period = 4;</code>
   */
  public java.lang.String getEndPeriod() {
    java.lang.Object ref = endPeriod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endPeriod_ = s;
      return s;
    }
  }
  /**
   * <code>string end_period = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEndPeriodBytes() {
    java.lang.Object ref = endPeriod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endPeriod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUPON_PERIOD_FIELD_NUMBER = 5;
  private long couponPeriod_;
  /**
   * <code>int64 coupon_period = 5;</code>
   */
  public long getCouponPeriod() {
    return couponPeriod_;
  }

  public static final int DAYS_FROM_DIST_FIELD_NUMBER = 6;
  private long daysFromDist_;
  /**
   * <code>int64 days_from_dist = 6;</code>
   */
  public long getDaysFromDist() {
    return daysFromDist_;
  }

  public static final int COUPON_RATE_FIELD_NUMBER = 7;
  private com.google.protobuf.DoubleValue couponRate_;
  /**
   * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
   */
  public boolean hasCouponRate() {
    return couponRate_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
   */
  public com.google.protobuf.DoubleValue getCouponRate() {
    return couponRate_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : couponRate_;
  }
  /**
   * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
   */
  public com.google.protobuf.DoubleValueOrBuilder getCouponRateOrBuilder() {
    return getCouponRate();
  }

  public static final int PAY_PER_BOUND_FIELD_NUMBER = 8;
  private com.google.protobuf.DoubleValue payPerBound_;
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
   */
  public boolean hasPayPerBound() {
    return payPerBound_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
   */
  public com.google.protobuf.DoubleValue getPayPerBound() {
    return payPerBound_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : payPerBound_;
  }
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
   */
  public com.google.protobuf.DoubleValueOrBuilder getPayPerBoundOrBuilder() {
    return getPayPerBound();
  }

  public static final int COUPON_VAL_FIELD_NUMBER = 9;
  private com.google.protobuf.DoubleValue couponVal_;
  /**
   * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
   */
  public boolean hasCouponVal() {
    return couponVal_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
   */
  public com.google.protobuf.DoubleValue getCouponVal() {
    return couponVal_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : couponVal_;
  }
  /**
   * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
   */
  public com.google.protobuf.DoubleValueOrBuilder getCouponValOrBuilder() {
    return getCouponVal();
  }

  public static final int STOP_TRADE_DATE_FIELD_NUMBER = 10;
  private volatile java.lang.Object stopTradeDate_;
  /**
   * <code>string stop_trade_date = 10;</code>
   */
  public java.lang.String getStopTradeDate() {
    java.lang.Object ref = stopTradeDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stopTradeDate_ = s;
      return s;
    }
  }
  /**
   * <code>string stop_trade_date = 10;</code>
   */
  public com.google.protobuf.ByteString
      getStopTradeDateBytes() {
    java.lang.Object ref = stopTradeDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stopTradeDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAY_DATE_FIELD_NUMBER = 11;
  private volatile java.lang.Object payDate_;
  /**
   * <code>string pay_date = 11;</code>
   */
  public java.lang.String getPayDate() {
    java.lang.Object ref = payDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      payDate_ = s;
      return s;
    }
  }
  /**
   * <code>string pay_date = 11;</code>
   */
  public com.google.protobuf.ByteString
      getPayDateBytes() {
    java.lang.Object ref = payDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      payDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUPON_RATE_DATE_FIELD_NUMBER = 12;
  private volatile java.lang.Object couponRateDate_;
  /**
   * <code>string coupon_rate_date = 12;</code>
   */
  public java.lang.String getCouponRateDate() {
    java.lang.Object ref = couponRateDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      couponRateDate_ = s;
      return s;
    }
  }
  /**
   * <code>string coupon_rate_date = 12;</code>
   */
  public com.google.protobuf.ByteString
      getCouponRateDateBytes() {
    java.lang.Object ref = couponRateDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      couponRateDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIX_DATE_FIELD_NUMBER = 13;
  private volatile java.lang.Object fixDate_;
  /**
   * <code>string fix_date = 13;</code>
   */
  public java.lang.String getFixDate() {
    java.lang.Object ref = fixDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fixDate_ = s;
      return s;
    }
  }
  /**
   * <code>string fix_date = 13;</code>
   */
  public com.google.protobuf.ByteString
      getFixDateBytes() {
    java.lang.Object ref = fixDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fixDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_DATE_FIELD_NUMBER = 14;
  private long updateDate_;
  /**
   * <code>int64 update_date = 14;</code>
   */
  public long getUpdateDate() {
    return updateDate_;
  }

  public static final int PAY_PER_BOND_FRAC_FIELD_NUMBER = 15;
  private com.google.protobuf.DoubleValue payPerBondFrac_;
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
   */
  public boolean hasPayPerBondFrac() {
    return payPerBondFrac_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
   */
  public com.google.protobuf.DoubleValue getPayPerBondFrac() {
    return payPerBondFrac_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : payPerBondFrac_;
  }
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
   */
  public com.google.protobuf.DoubleValueOrBuilder getPayPerBondFracOrBuilder() {
    return getPayPerBondFrac();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idFintool_ != 0L) {
      output.writeInt64(1, idFintool_);
    }
    if (idCoupon_ != 0L) {
      output.writeInt64(2, idCoupon_);
    }
    if (!getBeginPeriodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, beginPeriod_);
    }
    if (!getEndPeriodBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, endPeriod_);
    }
    if (couponPeriod_ != 0L) {
      output.writeInt64(5, couponPeriod_);
    }
    if (daysFromDist_ != 0L) {
      output.writeInt64(6, daysFromDist_);
    }
    if (couponRate_ != null) {
      output.writeMessage(7, getCouponRate());
    }
    if (payPerBound_ != null) {
      output.writeMessage(8, getPayPerBound());
    }
    if (couponVal_ != null) {
      output.writeMessage(9, getCouponVal());
    }
    if (!getStopTradeDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, stopTradeDate_);
    }
    if (!getPayDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, payDate_);
    }
    if (!getCouponRateDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, couponRateDate_);
    }
    if (!getFixDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, fixDate_);
    }
    if (updateDate_ != 0L) {
      output.writeInt64(14, updateDate_);
    }
    if (payPerBondFrac_ != null) {
      output.writeMessage(15, getPayPerBondFrac());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idFintool_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, idFintool_);
    }
    if (idCoupon_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, idCoupon_);
    }
    if (!getBeginPeriodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, beginPeriod_);
    }
    if (!getEndPeriodBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, endPeriod_);
    }
    if (couponPeriod_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, couponPeriod_);
    }
    if (daysFromDist_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, daysFromDist_);
    }
    if (couponRate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getCouponRate());
    }
    if (payPerBound_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getPayPerBound());
    }
    if (couponVal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getCouponVal());
    }
    if (!getStopTradeDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, stopTradeDate_);
    }
    if (!getPayDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, payDate_);
    }
    if (!getCouponRateDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, couponRateDate_);
    }
    if (!getFixDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, fixDate_);
    }
    if (updateDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, updateDate_);
    }
    if (payPerBondFrac_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getPayPerBondFrac());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons)) {
      return super.equals(obj);
    }
    com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons other = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons) obj;

    if (getIdFintool()
        != other.getIdFintool()) return false;
    if (getIdCoupon()
        != other.getIdCoupon()) return false;
    if (!getBeginPeriod()
        .equals(other.getBeginPeriod())) return false;
    if (!getEndPeriod()
        .equals(other.getEndPeriod())) return false;
    if (getCouponPeriod()
        != other.getCouponPeriod()) return false;
    if (getDaysFromDist()
        != other.getDaysFromDist()) return false;
    if (hasCouponRate() != other.hasCouponRate()) return false;
    if (hasCouponRate()) {
      if (!getCouponRate()
          .equals(other.getCouponRate())) return false;
    }
    if (hasPayPerBound() != other.hasPayPerBound()) return false;
    if (hasPayPerBound()) {
      if (!getPayPerBound()
          .equals(other.getPayPerBound())) return false;
    }
    if (hasCouponVal() != other.hasCouponVal()) return false;
    if (hasCouponVal()) {
      if (!getCouponVal()
          .equals(other.getCouponVal())) return false;
    }
    if (!getStopTradeDate()
        .equals(other.getStopTradeDate())) return false;
    if (!getPayDate()
        .equals(other.getPayDate())) return false;
    if (!getCouponRateDate()
        .equals(other.getCouponRateDate())) return false;
    if (!getFixDate()
        .equals(other.getFixDate())) return false;
    if (getUpdateDate()
        != other.getUpdateDate()) return false;
    if (hasPayPerBondFrac() != other.hasPayPerBondFrac()) return false;
    if (hasPayPerBondFrac()) {
      if (!getPayPerBondFrac()
          .equals(other.getPayPerBondFrac())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FINTOOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdFintool());
    hash = (37 * hash) + ID_COUPON_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdCoupon());
    hash = (37 * hash) + BEGIN_PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getBeginPeriod().hashCode();
    hash = (37 * hash) + END_PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getEndPeriod().hashCode();
    hash = (37 * hash) + COUPON_PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCouponPeriod());
    hash = (37 * hash) + DAYS_FROM_DIST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDaysFromDist());
    if (hasCouponRate()) {
      hash = (37 * hash) + COUPON_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getCouponRate().hashCode();
    }
    if (hasPayPerBound()) {
      hash = (37 * hash) + PAY_PER_BOUND_FIELD_NUMBER;
      hash = (53 * hash) + getPayPerBound().hashCode();
    }
    if (hasCouponVal()) {
      hash = (37 * hash) + COUPON_VAL_FIELD_NUMBER;
      hash = (53 * hash) + getCouponVal().hashCode();
    }
    hash = (37 * hash) + STOP_TRADE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getStopTradeDate().hashCode();
    hash = (37 * hash) + PAY_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getPayDate().hashCode();
    hash = (37 * hash) + COUPON_RATE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getCouponRateDate().hashCode();
    hash = (37 * hash) + FIX_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getFixDate().hashCode();
    hash = (37 * hash) + UPDATE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateDate());
    if (hasPayPerBondFrac()) {
      hash = (37 * hash) + PAY_PER_BOND_FRAC_FIELD_NUMBER;
      hash = (53 * hash) + getPayPerBondFrac().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BondCoupons}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BondCoupons)
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCouponsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondCoupons_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondCoupons_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons.Builder.class);
    }

    // Construct using com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idFintool_ = 0L;

      idCoupon_ = 0L;

      beginPeriod_ = "";

      endPeriod_ = "";

      couponPeriod_ = 0L;

      daysFromDist_ = 0L;

      if (couponRateBuilder_ == null) {
        couponRate_ = null;
      } else {
        couponRate_ = null;
        couponRateBuilder_ = null;
      }
      if (payPerBoundBuilder_ == null) {
        payPerBound_ = null;
      } else {
        payPerBound_ = null;
        payPerBoundBuilder_ = null;
      }
      if (couponValBuilder_ == null) {
        couponVal_ = null;
      } else {
        couponVal_ = null;
        couponValBuilder_ = null;
      }
      stopTradeDate_ = "";

      payDate_ = "";

      couponRateDate_ = "";

      fixDate_ = "";

      updateDate_ = 0L;

      if (payPerBondFracBuilder_ == null) {
        payPerBondFrac_ = null;
      } else {
        payPerBondFrac_ = null;
        payPerBondFracBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondCoupons_descriptor;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons getDefaultInstanceForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons.getDefaultInstance();
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons build() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons buildPartial() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons result = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons(this);
      result.idFintool_ = idFintool_;
      result.idCoupon_ = idCoupon_;
      result.beginPeriod_ = beginPeriod_;
      result.endPeriod_ = endPeriod_;
      result.couponPeriod_ = couponPeriod_;
      result.daysFromDist_ = daysFromDist_;
      if (couponRateBuilder_ == null) {
        result.couponRate_ = couponRate_;
      } else {
        result.couponRate_ = couponRateBuilder_.build();
      }
      if (payPerBoundBuilder_ == null) {
        result.payPerBound_ = payPerBound_;
      } else {
        result.payPerBound_ = payPerBoundBuilder_.build();
      }
      if (couponValBuilder_ == null) {
        result.couponVal_ = couponVal_;
      } else {
        result.couponVal_ = couponValBuilder_.build();
      }
      result.stopTradeDate_ = stopTradeDate_;
      result.payDate_ = payDate_;
      result.couponRateDate_ = couponRateDate_;
      result.fixDate_ = fixDate_;
      result.updateDate_ = updateDate_;
      if (payPerBondFracBuilder_ == null) {
        result.payPerBondFrac_ = payPerBondFrac_;
      } else {
        result.payPerBondFrac_ = payPerBondFracBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons) {
        return mergeFrom((com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons other) {
      if (other == com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons.getDefaultInstance()) return this;
      if (other.getIdFintool() != 0L) {
        setIdFintool(other.getIdFintool());
      }
      if (other.getIdCoupon() != 0L) {
        setIdCoupon(other.getIdCoupon());
      }
      if (!other.getBeginPeriod().isEmpty()) {
        beginPeriod_ = other.beginPeriod_;
        onChanged();
      }
      if (!other.getEndPeriod().isEmpty()) {
        endPeriod_ = other.endPeriod_;
        onChanged();
      }
      if (other.getCouponPeriod() != 0L) {
        setCouponPeriod(other.getCouponPeriod());
      }
      if (other.getDaysFromDist() != 0L) {
        setDaysFromDist(other.getDaysFromDist());
      }
      if (other.hasCouponRate()) {
        mergeCouponRate(other.getCouponRate());
      }
      if (other.hasPayPerBound()) {
        mergePayPerBound(other.getPayPerBound());
      }
      if (other.hasCouponVal()) {
        mergeCouponVal(other.getCouponVal());
      }
      if (!other.getStopTradeDate().isEmpty()) {
        stopTradeDate_ = other.stopTradeDate_;
        onChanged();
      }
      if (!other.getPayDate().isEmpty()) {
        payDate_ = other.payDate_;
        onChanged();
      }
      if (!other.getCouponRateDate().isEmpty()) {
        couponRateDate_ = other.couponRateDate_;
        onChanged();
      }
      if (!other.getFixDate().isEmpty()) {
        fixDate_ = other.fixDate_;
        onChanged();
      }
      if (other.getUpdateDate() != 0L) {
        setUpdateDate(other.getUpdateDate());
      }
      if (other.hasPayPerBondFrac()) {
        mergePayPerBondFrac(other.getPayPerBondFrac());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long idFintool_ ;
    /**
     * <code>int64 id_fintool = 1;</code>
     */
    public long getIdFintool() {
      return idFintool_;
    }
    /**
     * <code>int64 id_fintool = 1;</code>
     */
    public Builder setIdFintool(long value) {
      
      idFintool_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id_fintool = 1;</code>
     */
    public Builder clearIdFintool() {
      
      idFintool_ = 0L;
      onChanged();
      return this;
    }

    private long idCoupon_ ;
    /**
     * <code>int64 id_coupon = 2;</code>
     */
    public long getIdCoupon() {
      return idCoupon_;
    }
    /**
     * <code>int64 id_coupon = 2;</code>
     */
    public Builder setIdCoupon(long value) {
      
      idCoupon_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id_coupon = 2;</code>
     */
    public Builder clearIdCoupon() {
      
      idCoupon_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object beginPeriod_ = "";
    /**
     * <code>string begin_period = 3;</code>
     */
    public java.lang.String getBeginPeriod() {
      java.lang.Object ref = beginPeriod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        beginPeriod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string begin_period = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBeginPeriodBytes() {
      java.lang.Object ref = beginPeriod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        beginPeriod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string begin_period = 3;</code>
     */
    public Builder setBeginPeriod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      beginPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string begin_period = 3;</code>
     */
    public Builder clearBeginPeriod() {
      
      beginPeriod_ = getDefaultInstance().getBeginPeriod();
      onChanged();
      return this;
    }
    /**
     * <code>string begin_period = 3;</code>
     */
    public Builder setBeginPeriodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      beginPeriod_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endPeriod_ = "";
    /**
     * <code>string end_period = 4;</code>
     */
    public java.lang.String getEndPeriod() {
      java.lang.Object ref = endPeriod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endPeriod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string end_period = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEndPeriodBytes() {
      java.lang.Object ref = endPeriod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endPeriod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string end_period = 4;</code>
     */
    public Builder setEndPeriod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string end_period = 4;</code>
     */
    public Builder clearEndPeriod() {
      
      endPeriod_ = getDefaultInstance().getEndPeriod();
      onChanged();
      return this;
    }
    /**
     * <code>string end_period = 4;</code>
     */
    public Builder setEndPeriodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endPeriod_ = value;
      onChanged();
      return this;
    }

    private long couponPeriod_ ;
    /**
     * <code>int64 coupon_period = 5;</code>
     */
    public long getCouponPeriod() {
      return couponPeriod_;
    }
    /**
     * <code>int64 coupon_period = 5;</code>
     */
    public Builder setCouponPeriod(long value) {
      
      couponPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 coupon_period = 5;</code>
     */
    public Builder clearCouponPeriod() {
      
      couponPeriod_ = 0L;
      onChanged();
      return this;
    }

    private long daysFromDist_ ;
    /**
     * <code>int64 days_from_dist = 6;</code>
     */
    public long getDaysFromDist() {
      return daysFromDist_;
    }
    /**
     * <code>int64 days_from_dist = 6;</code>
     */
    public Builder setDaysFromDist(long value) {
      
      daysFromDist_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 days_from_dist = 6;</code>
     */
    public Builder clearDaysFromDist() {
      
      daysFromDist_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.DoubleValue couponRate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> couponRateBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public boolean hasCouponRate() {
      return couponRateBuilder_ != null || couponRate_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public com.google.protobuf.DoubleValue getCouponRate() {
      if (couponRateBuilder_ == null) {
        return couponRate_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : couponRate_;
      } else {
        return couponRateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public Builder setCouponRate(com.google.protobuf.DoubleValue value) {
      if (couponRateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        couponRate_ = value;
        onChanged();
      } else {
        couponRateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public Builder setCouponRate(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (couponRateBuilder_ == null) {
        couponRate_ = builderForValue.build();
        onChanged();
      } else {
        couponRateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public Builder mergeCouponRate(com.google.protobuf.DoubleValue value) {
      if (couponRateBuilder_ == null) {
        if (couponRate_ != null) {
          couponRate_ =
            com.google.protobuf.DoubleValue.newBuilder(couponRate_).mergeFrom(value).buildPartial();
        } else {
          couponRate_ = value;
        }
        onChanged();
      } else {
        couponRateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public Builder clearCouponRate() {
      if (couponRateBuilder_ == null) {
        couponRate_ = null;
        onChanged();
      } else {
        couponRate_ = null;
        couponRateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getCouponRateBuilder() {
      
      onChanged();
      return getCouponRateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getCouponRateOrBuilder() {
      if (couponRateBuilder_ != null) {
        return couponRateBuilder_.getMessageOrBuilder();
      } else {
        return couponRate_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : couponRate_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_rate = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getCouponRateFieldBuilder() {
      if (couponRateBuilder_ == null) {
        couponRateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getCouponRate(),
                getParentForChildren(),
                isClean());
        couponRate_ = null;
      }
      return couponRateBuilder_;
    }

    private com.google.protobuf.DoubleValue payPerBound_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> payPerBoundBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public boolean hasPayPerBound() {
      return payPerBoundBuilder_ != null || payPerBound_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public com.google.protobuf.DoubleValue getPayPerBound() {
      if (payPerBoundBuilder_ == null) {
        return payPerBound_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : payPerBound_;
      } else {
        return payPerBoundBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public Builder setPayPerBound(com.google.protobuf.DoubleValue value) {
      if (payPerBoundBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payPerBound_ = value;
        onChanged();
      } else {
        payPerBoundBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public Builder setPayPerBound(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (payPerBoundBuilder_ == null) {
        payPerBound_ = builderForValue.build();
        onChanged();
      } else {
        payPerBoundBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public Builder mergePayPerBound(com.google.protobuf.DoubleValue value) {
      if (payPerBoundBuilder_ == null) {
        if (payPerBound_ != null) {
          payPerBound_ =
            com.google.protobuf.DoubleValue.newBuilder(payPerBound_).mergeFrom(value).buildPartial();
        } else {
          payPerBound_ = value;
        }
        onChanged();
      } else {
        payPerBoundBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public Builder clearPayPerBound() {
      if (payPerBoundBuilder_ == null) {
        payPerBound_ = null;
        onChanged();
      } else {
        payPerBound_ = null;
        payPerBoundBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getPayPerBoundBuilder() {
      
      onChanged();
      return getPayPerBoundFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getPayPerBoundOrBuilder() {
      if (payPerBoundBuilder_ != null) {
        return payPerBoundBuilder_.getMessageOrBuilder();
      } else {
        return payPerBound_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : payPerBound_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bound = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getPayPerBoundFieldBuilder() {
      if (payPerBoundBuilder_ == null) {
        payPerBoundBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getPayPerBound(),
                getParentForChildren(),
                isClean());
        payPerBound_ = null;
      }
      return payPerBoundBuilder_;
    }

    private com.google.protobuf.DoubleValue couponVal_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> couponValBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public boolean hasCouponVal() {
      return couponValBuilder_ != null || couponVal_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public com.google.protobuf.DoubleValue getCouponVal() {
      if (couponValBuilder_ == null) {
        return couponVal_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : couponVal_;
      } else {
        return couponValBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public Builder setCouponVal(com.google.protobuf.DoubleValue value) {
      if (couponValBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        couponVal_ = value;
        onChanged();
      } else {
        couponValBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public Builder setCouponVal(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (couponValBuilder_ == null) {
        couponVal_ = builderForValue.build();
        onChanged();
      } else {
        couponValBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public Builder mergeCouponVal(com.google.protobuf.DoubleValue value) {
      if (couponValBuilder_ == null) {
        if (couponVal_ != null) {
          couponVal_ =
            com.google.protobuf.DoubleValue.newBuilder(couponVal_).mergeFrom(value).buildPartial();
        } else {
          couponVal_ = value;
        }
        onChanged();
      } else {
        couponValBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public Builder clearCouponVal() {
      if (couponValBuilder_ == null) {
        couponVal_ = null;
        onChanged();
      } else {
        couponVal_ = null;
        couponValBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getCouponValBuilder() {
      
      onChanged();
      return getCouponValFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getCouponValOrBuilder() {
      if (couponValBuilder_ != null) {
        return couponValBuilder_.getMessageOrBuilder();
      } else {
        return couponVal_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : couponVal_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue coupon_val = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getCouponValFieldBuilder() {
      if (couponValBuilder_ == null) {
        couponValBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getCouponVal(),
                getParentForChildren(),
                isClean());
        couponVal_ = null;
      }
      return couponValBuilder_;
    }

    private java.lang.Object stopTradeDate_ = "";
    /**
     * <code>string stop_trade_date = 10;</code>
     */
    public java.lang.String getStopTradeDate() {
      java.lang.Object ref = stopTradeDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stopTradeDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stop_trade_date = 10;</code>
     */
    public com.google.protobuf.ByteString
        getStopTradeDateBytes() {
      java.lang.Object ref = stopTradeDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stopTradeDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stop_trade_date = 10;</code>
     */
    public Builder setStopTradeDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      stopTradeDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string stop_trade_date = 10;</code>
     */
    public Builder clearStopTradeDate() {
      
      stopTradeDate_ = getDefaultInstance().getStopTradeDate();
      onChanged();
      return this;
    }
    /**
     * <code>string stop_trade_date = 10;</code>
     */
    public Builder setStopTradeDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      stopTradeDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object payDate_ = "";
    /**
     * <code>string pay_date = 11;</code>
     */
    public java.lang.String getPayDate() {
      java.lang.Object ref = payDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        payDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pay_date = 11;</code>
     */
    public com.google.protobuf.ByteString
        getPayDateBytes() {
      java.lang.Object ref = payDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pay_date = 11;</code>
     */
    public Builder setPayDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pay_date = 11;</code>
     */
    public Builder clearPayDate() {
      
      payDate_ = getDefaultInstance().getPayDate();
      onChanged();
      return this;
    }
    /**
     * <code>string pay_date = 11;</code>
     */
    public Builder setPayDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      payDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object couponRateDate_ = "";
    /**
     * <code>string coupon_rate_date = 12;</code>
     */
    public java.lang.String getCouponRateDate() {
      java.lang.Object ref = couponRateDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        couponRateDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string coupon_rate_date = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCouponRateDateBytes() {
      java.lang.Object ref = couponRateDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        couponRateDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string coupon_rate_date = 12;</code>
     */
    public Builder setCouponRateDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      couponRateDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string coupon_rate_date = 12;</code>
     */
    public Builder clearCouponRateDate() {
      
      couponRateDate_ = getDefaultInstance().getCouponRateDate();
      onChanged();
      return this;
    }
    /**
     * <code>string coupon_rate_date = 12;</code>
     */
    public Builder setCouponRateDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      couponRateDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fixDate_ = "";
    /**
     * <code>string fix_date = 13;</code>
     */
    public java.lang.String getFixDate() {
      java.lang.Object ref = fixDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fixDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fix_date = 13;</code>
     */
    public com.google.protobuf.ByteString
        getFixDateBytes() {
      java.lang.Object ref = fixDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fixDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fix_date = 13;</code>
     */
    public Builder setFixDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fixDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fix_date = 13;</code>
     */
    public Builder clearFixDate() {
      
      fixDate_ = getDefaultInstance().getFixDate();
      onChanged();
      return this;
    }
    /**
     * <code>string fix_date = 13;</code>
     */
    public Builder setFixDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fixDate_ = value;
      onChanged();
      return this;
    }

    private long updateDate_ ;
    /**
     * <code>int64 update_date = 14;</code>
     */
    public long getUpdateDate() {
      return updateDate_;
    }
    /**
     * <code>int64 update_date = 14;</code>
     */
    public Builder setUpdateDate(long value) {
      
      updateDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 update_date = 14;</code>
     */
    public Builder clearUpdateDate() {
      
      updateDate_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.DoubleValue payPerBondFrac_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> payPerBondFracBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public boolean hasPayPerBondFrac() {
      return payPerBondFracBuilder_ != null || payPerBondFrac_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public com.google.protobuf.DoubleValue getPayPerBondFrac() {
      if (payPerBondFracBuilder_ == null) {
        return payPerBondFrac_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : payPerBondFrac_;
      } else {
        return payPerBondFracBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public Builder setPayPerBondFrac(com.google.protobuf.DoubleValue value) {
      if (payPerBondFracBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payPerBondFrac_ = value;
        onChanged();
      } else {
        payPerBondFracBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public Builder setPayPerBondFrac(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (payPerBondFracBuilder_ == null) {
        payPerBondFrac_ = builderForValue.build();
        onChanged();
      } else {
        payPerBondFracBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public Builder mergePayPerBondFrac(com.google.protobuf.DoubleValue value) {
      if (payPerBondFracBuilder_ == null) {
        if (payPerBondFrac_ != null) {
          payPerBondFrac_ =
            com.google.protobuf.DoubleValue.newBuilder(payPerBondFrac_).mergeFrom(value).buildPartial();
        } else {
          payPerBondFrac_ = value;
        }
        onChanged();
      } else {
        payPerBondFracBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public Builder clearPayPerBondFrac() {
      if (payPerBondFracBuilder_ == null) {
        payPerBondFrac_ = null;
        onChanged();
      } else {
        payPerBondFrac_ = null;
        payPerBondFracBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getPayPerBondFracBuilder() {
      
      onChanged();
      return getPayPerBondFracFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getPayPerBondFracOrBuilder() {
      if (payPerBondFracBuilder_ != null) {
        return payPerBondFracBuilder_.getMessageOrBuilder();
      } else {
        return payPerBondFrac_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : payPerBondFrac_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue pay_per_bond_frac = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getPayPerBondFracFieldBuilder() {
      if (payPerBondFracBuilder_ == null) {
        payPerBondFracBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getPayPerBondFrac(),
                getParentForChildren(),
                isClean());
        payPerBondFrac_ = null;
      }
      return payPerBondFracBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BondCoupons)
  }

  // @@protoc_insertion_point(class_scope:BondCoupons)
  private static final com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons();
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BondCoupons>
      PARSER = new com.google.protobuf.AbstractParser<BondCoupons>() {
    @java.lang.Override
    public BondCoupons parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BondCoupons(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BondCoupons> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BondCoupons> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondCoupons getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

