// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface BondConvertationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BondConvertation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id_fintool = 1;</code>
   */
  long getIdFintool();

  /**
   * <code>int64 id_fintool_alter = 2;</code>
   */
  long getIdFintoolAlter();

  /**
   * <code>string begconv_date = 3;</code>
   */
  java.lang.String getBegconvDate();
  /**
   * <code>string begconv_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getBegconvDateBytes();

  /**
   * <code>string endconv_date = 4;</code>
   */
  java.lang.String getEndconvDate();
  /**
   * <code>string endconv_date = 4;</code>
   */
  com.google.protobuf.ByteString
      getEndconvDateBytes();

  /**
   * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
   */
  boolean hasCoefficient();
  /**
   * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
   */
  com.google.protobuf.DoubleValue getCoefficient();
  /**
   * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getCoefficientOrBuilder();

  /**
   * <code>int64 update_date = 6;</code>
   */
  long getUpdateDate();
}
