// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

/**
 * Protobuf type {@code BondConvertation}
 */
public  final class BondConvertation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BondConvertation)
    BondConvertationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BondConvertation.newBuilder() to construct.
  private BondConvertation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BondConvertation() {
    begconvDate_ = "";
    endconvDate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BondConvertation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BondConvertation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            idFintool_ = input.readInt64();
            break;
          }
          case 16: {

            idFintoolAlter_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            begconvDate_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            endconvDate_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (coefficient_ != null) {
              subBuilder = coefficient_.toBuilder();
            }
            coefficient_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(coefficient_);
              coefficient_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            updateDate_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondConvertation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondConvertation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation.Builder.class);
  }

  public static final int ID_FINTOOL_FIELD_NUMBER = 1;
  private long idFintool_;
  /**
   * <code>int64 id_fintool = 1;</code>
   */
  public long getIdFintool() {
    return idFintool_;
  }

  public static final int ID_FINTOOL_ALTER_FIELD_NUMBER = 2;
  private long idFintoolAlter_;
  /**
   * <code>int64 id_fintool_alter = 2;</code>
   */
  public long getIdFintoolAlter() {
    return idFintoolAlter_;
  }

  public static final int BEGCONV_DATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object begconvDate_;
  /**
   * <code>string begconv_date = 3;</code>
   */
  public java.lang.String getBegconvDate() {
    java.lang.Object ref = begconvDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      begconvDate_ = s;
      return s;
    }
  }
  /**
   * <code>string begconv_date = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBegconvDateBytes() {
    java.lang.Object ref = begconvDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      begconvDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDCONV_DATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object endconvDate_;
  /**
   * <code>string endconv_date = 4;</code>
   */
  public java.lang.String getEndconvDate() {
    java.lang.Object ref = endconvDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endconvDate_ = s;
      return s;
    }
  }
  /**
   * <code>string endconv_date = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEndconvDateBytes() {
    java.lang.Object ref = endconvDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endconvDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COEFFICIENT_FIELD_NUMBER = 5;
  private com.google.protobuf.DoubleValue coefficient_;
  /**
   * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
   */
  public boolean hasCoefficient() {
    return coefficient_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
   */
  public com.google.protobuf.DoubleValue getCoefficient() {
    return coefficient_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : coefficient_;
  }
  /**
   * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
   */
  public com.google.protobuf.DoubleValueOrBuilder getCoefficientOrBuilder() {
    return getCoefficient();
  }

  public static final int UPDATE_DATE_FIELD_NUMBER = 6;
  private long updateDate_;
  /**
   * <code>int64 update_date = 6;</code>
   */
  public long getUpdateDate() {
    return updateDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idFintool_ != 0L) {
      output.writeInt64(1, idFintool_);
    }
    if (idFintoolAlter_ != 0L) {
      output.writeInt64(2, idFintoolAlter_);
    }
    if (!getBegconvDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, begconvDate_);
    }
    if (!getEndconvDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, endconvDate_);
    }
    if (coefficient_ != null) {
      output.writeMessage(5, getCoefficient());
    }
    if (updateDate_ != 0L) {
      output.writeInt64(6, updateDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idFintool_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, idFintool_);
    }
    if (idFintoolAlter_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, idFintoolAlter_);
    }
    if (!getBegconvDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, begconvDate_);
    }
    if (!getEndconvDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, endconvDate_);
    }
    if (coefficient_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCoefficient());
    }
    if (updateDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, updateDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation)) {
      return super.equals(obj);
    }
    com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation other = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation) obj;

    if (getIdFintool()
        != other.getIdFintool()) return false;
    if (getIdFintoolAlter()
        != other.getIdFintoolAlter()) return false;
    if (!getBegconvDate()
        .equals(other.getBegconvDate())) return false;
    if (!getEndconvDate()
        .equals(other.getEndconvDate())) return false;
    if (hasCoefficient() != other.hasCoefficient()) return false;
    if (hasCoefficient()) {
      if (!getCoefficient()
          .equals(other.getCoefficient())) return false;
    }
    if (getUpdateDate()
        != other.getUpdateDate()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FINTOOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdFintool());
    hash = (37 * hash) + ID_FINTOOL_ALTER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdFintoolAlter());
    hash = (37 * hash) + BEGCONV_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getBegconvDate().hashCode();
    hash = (37 * hash) + ENDCONV_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getEndconvDate().hashCode();
    if (hasCoefficient()) {
      hash = (37 * hash) + COEFFICIENT_FIELD_NUMBER;
      hash = (53 * hash) + getCoefficient().hashCode();
    }
    hash = (37 * hash) + UPDATE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUpdateDate());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BondConvertation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BondConvertation)
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondConvertation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondConvertation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation.Builder.class);
    }

    // Construct using com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      idFintool_ = 0L;

      idFintoolAlter_ = 0L;

      begconvDate_ = "";

      endconvDate_ = "";

      if (coefficientBuilder_ == null) {
        coefficient_ = null;
      } else {
        coefficient_ = null;
        coefficientBuilder_ = null;
      }
      updateDate_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_BondConvertation_descriptor;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation getDefaultInstanceForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation.getDefaultInstance();
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation build() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation buildPartial() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation result = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation(this);
      result.idFintool_ = idFintool_;
      result.idFintoolAlter_ = idFintoolAlter_;
      result.begconvDate_ = begconvDate_;
      result.endconvDate_ = endconvDate_;
      if (coefficientBuilder_ == null) {
        result.coefficient_ = coefficient_;
      } else {
        result.coefficient_ = coefficientBuilder_.build();
      }
      result.updateDate_ = updateDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation) {
        return mergeFrom((com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation other) {
      if (other == com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation.getDefaultInstance()) return this;
      if (other.getIdFintool() != 0L) {
        setIdFintool(other.getIdFintool());
      }
      if (other.getIdFintoolAlter() != 0L) {
        setIdFintoolAlter(other.getIdFintoolAlter());
      }
      if (!other.getBegconvDate().isEmpty()) {
        begconvDate_ = other.begconvDate_;
        onChanged();
      }
      if (!other.getEndconvDate().isEmpty()) {
        endconvDate_ = other.endconvDate_;
        onChanged();
      }
      if (other.hasCoefficient()) {
        mergeCoefficient(other.getCoefficient());
      }
      if (other.getUpdateDate() != 0L) {
        setUpdateDate(other.getUpdateDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long idFintool_ ;
    /**
     * <code>int64 id_fintool = 1;</code>
     */
    public long getIdFintool() {
      return idFintool_;
    }
    /**
     * <code>int64 id_fintool = 1;</code>
     */
    public Builder setIdFintool(long value) {
      
      idFintool_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id_fintool = 1;</code>
     */
    public Builder clearIdFintool() {
      
      idFintool_ = 0L;
      onChanged();
      return this;
    }

    private long idFintoolAlter_ ;
    /**
     * <code>int64 id_fintool_alter = 2;</code>
     */
    public long getIdFintoolAlter() {
      return idFintoolAlter_;
    }
    /**
     * <code>int64 id_fintool_alter = 2;</code>
     */
    public Builder setIdFintoolAlter(long value) {
      
      idFintoolAlter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id_fintool_alter = 2;</code>
     */
    public Builder clearIdFintoolAlter() {
      
      idFintoolAlter_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object begconvDate_ = "";
    /**
     * <code>string begconv_date = 3;</code>
     */
    public java.lang.String getBegconvDate() {
      java.lang.Object ref = begconvDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        begconvDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string begconv_date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBegconvDateBytes() {
      java.lang.Object ref = begconvDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        begconvDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string begconv_date = 3;</code>
     */
    public Builder setBegconvDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      begconvDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string begconv_date = 3;</code>
     */
    public Builder clearBegconvDate() {
      
      begconvDate_ = getDefaultInstance().getBegconvDate();
      onChanged();
      return this;
    }
    /**
     * <code>string begconv_date = 3;</code>
     */
    public Builder setBegconvDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      begconvDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endconvDate_ = "";
    /**
     * <code>string endconv_date = 4;</code>
     */
    public java.lang.String getEndconvDate() {
      java.lang.Object ref = endconvDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endconvDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string endconv_date = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEndconvDateBytes() {
      java.lang.Object ref = endconvDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endconvDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string endconv_date = 4;</code>
     */
    public Builder setEndconvDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endconvDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string endconv_date = 4;</code>
     */
    public Builder clearEndconvDate() {
      
      endconvDate_ = getDefaultInstance().getEndconvDate();
      onChanged();
      return this;
    }
    /**
     * <code>string endconv_date = 4;</code>
     */
    public Builder setEndconvDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endconvDate_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.DoubleValue coefficient_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> coefficientBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public boolean hasCoefficient() {
      return coefficientBuilder_ != null || coefficient_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public com.google.protobuf.DoubleValue getCoefficient() {
      if (coefficientBuilder_ == null) {
        return coefficient_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : coefficient_;
      } else {
        return coefficientBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public Builder setCoefficient(com.google.protobuf.DoubleValue value) {
      if (coefficientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coefficient_ = value;
        onChanged();
      } else {
        coefficientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public Builder setCoefficient(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (coefficientBuilder_ == null) {
        coefficient_ = builderForValue.build();
        onChanged();
      } else {
        coefficientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public Builder mergeCoefficient(com.google.protobuf.DoubleValue value) {
      if (coefficientBuilder_ == null) {
        if (coefficient_ != null) {
          coefficient_ =
            com.google.protobuf.DoubleValue.newBuilder(coefficient_).mergeFrom(value).buildPartial();
        } else {
          coefficient_ = value;
        }
        onChanged();
      } else {
        coefficientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public Builder clearCoefficient() {
      if (coefficientBuilder_ == null) {
        coefficient_ = null;
        onChanged();
      } else {
        coefficient_ = null;
        coefficientBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getCoefficientBuilder() {
      
      onChanged();
      return getCoefficientFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getCoefficientOrBuilder() {
      if (coefficientBuilder_ != null) {
        return coefficientBuilder_.getMessageOrBuilder();
      } else {
        return coefficient_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : coefficient_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue coefficient = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getCoefficientFieldBuilder() {
      if (coefficientBuilder_ == null) {
        coefficientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getCoefficient(),
                getParentForChildren(),
                isClean());
        coefficient_ = null;
      }
      return coefficientBuilder_;
    }

    private long updateDate_ ;
    /**
     * <code>int64 update_date = 6;</code>
     */
    public long getUpdateDate() {
      return updateDate_;
    }
    /**
     * <code>int64 update_date = 6;</code>
     */
    public Builder setUpdateDate(long value) {
      
      updateDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 update_date = 6;</code>
     */
    public Builder clearUpdateDate() {
      
      updateDate_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BondConvertation)
  }

  // @@protoc_insertion_point(class_scope:BondConvertation)
  private static final com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation();
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BondConvertation>
      PARSER = new com.google.protobuf.AbstractParser<BondConvertation>() {
    @java.lang.Override
    public BondConvertation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BondConvertation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BondConvertation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BondConvertation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.BondConvertation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

