// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface BondMaturitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BondMaturities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fintoolid = 1;</code>
   */
  long getFintoolid();

  /**
   * <code>string isin = 2;</code>
   */
  java.lang.String getIsin();
  /**
   * <code>string isin = 2;</code>
   */
  com.google.protobuf.ByteString
      getIsinBytes();

  /**
   * <code>string mty_date = 3;</code>
   */
  java.lang.String getMtyDate();
  /**
   * <code>string mty_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getMtyDateBytes();

  /**
   * <code>.google.protobuf.DoubleValue pay_per_bond = 4;</code>
   */
  boolean hasPayPerBond();
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bond = 4;</code>
   */
  com.google.protobuf.DoubleValue getPayPerBond();
  /**
   * <code>.google.protobuf.DoubleValue pay_per_bond = 4;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getPayPerBondOrBuilder();

  /**
   * <code>int64 update_date = 5;</code>
   */
  long getUpdateDate();
}
