// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface CorporateActionKindsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CorporateActionKindsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   */
  java.lang.String getReqId();
  /**
   * <code>string reqId = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>repeated .CorporateActionKind corporateActionKinds = 2;</code>
   */
  java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKind> 
      getCorporateActionKindsList();
  /**
   * <code>repeated .CorporateActionKind corporateActionKinds = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKind getCorporateActionKinds(int index);
  /**
   * <code>repeated .CorporateActionKind corporateActionKinds = 2;</code>
   */
  int getCorporateActionKindsCount();
  /**
   * <code>repeated .CorporateActionKind corporateActionKinds = 2;</code>
   */
  java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKindOrBuilder> 
      getCorporateActionKindsOrBuilderList();
  /**
   * <code>repeated .CorporateActionKind corporateActionKinds = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKindOrBuilder getCorporateActionKindsOrBuilder(
      int index);
}
