// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface CorporateActionKindGroupsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CorporateActionKindGroups)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string name_rus = 2;</code>
   */
  java.lang.String getNameRus();
  /**
   * <code>string name_rus = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameRusBytes();

  /**
   * <code>string name_eng = 3;</code>
   */
  java.lang.String getNameEng();
  /**
   * <code>string name_eng = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameEngBytes();

  /**
   * <code>int64 order_group = 4;</code>
   */
  long getOrderGroup();

  /**
   * <code>int64 update_date = 5;</code>
   */
  long getUpdateDate();
}
