// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

/**
 * Protobuf type {@code CorporateActionSourcesResponse}
 */
public  final class CorporateActionSourcesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CorporateActionSourcesResponse)
    CorporateActionSourcesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CorporateActionSourcesResponse.newBuilder() to construct.
  private CorporateActionSourcesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CorporateActionSourcesResponse() {
    reqId_ = "";
    corporateActionSources_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CorporateActionSourcesResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CorporateActionSourcesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reqId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              corporateActionSources_ = new java.util.ArrayList<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource>();
              mutable_bitField0_ |= 0x00000001;
            }
            corporateActionSources_.add(
                input.readMessage(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        corporateActionSources_ = java.util.Collections.unmodifiableList(corporateActionSources_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_CorporateActionSourcesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_CorporateActionSourcesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse.Builder.class);
  }

  public static final int REQID_FIELD_NUMBER = 1;
  private volatile java.lang.Object reqId_;
  /**
   * <code>string reqId = 1;</code>
   */
  public java.lang.String getReqId() {
    java.lang.Object ref = reqId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reqId_ = s;
      return s;
    }
  }
  /**
   * <code>string reqId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReqIdBytes() {
    java.lang.Object ref = reqId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CORPORATEACTIONSOURCES_FIELD_NUMBER = 2;
  private java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource> corporateActionSources_;
  /**
   * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
   */
  public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource> getCorporateActionSourcesList() {
    return corporateActionSources_;
  }
  /**
   * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
   */
  public java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourceOrBuilder> 
      getCorporateActionSourcesOrBuilderList() {
    return corporateActionSources_;
  }
  /**
   * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
   */
  public int getCorporateActionSourcesCount() {
    return corporateActionSources_.size();
  }
  /**
   * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
   */
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource getCorporateActionSources(int index) {
    return corporateActionSources_.get(index);
  }
  /**
   * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
   */
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourceOrBuilder getCorporateActionSourcesOrBuilder(
      int index) {
    return corporateActionSources_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReqIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqId_);
    }
    for (int i = 0; i < corporateActionSources_.size(); i++) {
      output.writeMessage(2, corporateActionSources_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReqIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqId_);
    }
    for (int i = 0; i < corporateActionSources_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, corporateActionSources_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse)) {
      return super.equals(obj);
    }
    com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse other = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse) obj;

    if (!getReqId()
        .equals(other.getReqId())) return false;
    if (!getCorporateActionSourcesList()
        .equals(other.getCorporateActionSourcesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + getReqId().hashCode();
    if (getCorporateActionSourcesCount() > 0) {
      hash = (37 * hash) + CORPORATEACTIONSOURCES_FIELD_NUMBER;
      hash = (53 * hash) + getCorporateActionSourcesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CorporateActionSourcesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CorporateActionSourcesResponse)
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_CorporateActionSourcesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_CorporateActionSourcesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse.Builder.class);
    }

    // Construct using com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCorporateActionSourcesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reqId_ = "";

      if (corporateActionSourcesBuilder_ == null) {
        corporateActionSources_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        corporateActionSourcesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_CorporateActionSourcesResponse_descriptor;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse getDefaultInstanceForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse build() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse buildPartial() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse result = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse(this);
      int from_bitField0_ = bitField0_;
      result.reqId_ = reqId_;
      if (corporateActionSourcesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          corporateActionSources_ = java.util.Collections.unmodifiableList(corporateActionSources_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.corporateActionSources_ = corporateActionSources_;
      } else {
        result.corporateActionSources_ = corporateActionSourcesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse) {
        return mergeFrom((com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse other) {
      if (other == com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse.getDefaultInstance()) return this;
      if (!other.getReqId().isEmpty()) {
        reqId_ = other.reqId_;
        onChanged();
      }
      if (corporateActionSourcesBuilder_ == null) {
        if (!other.corporateActionSources_.isEmpty()) {
          if (corporateActionSources_.isEmpty()) {
            corporateActionSources_ = other.corporateActionSources_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCorporateActionSourcesIsMutable();
            corporateActionSources_.addAll(other.corporateActionSources_);
          }
          onChanged();
        }
      } else {
        if (!other.corporateActionSources_.isEmpty()) {
          if (corporateActionSourcesBuilder_.isEmpty()) {
            corporateActionSourcesBuilder_.dispose();
            corporateActionSourcesBuilder_ = null;
            corporateActionSources_ = other.corporateActionSources_;
            bitField0_ = (bitField0_ & ~0x00000001);
            corporateActionSourcesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCorporateActionSourcesFieldBuilder() : null;
          } else {
            corporateActionSourcesBuilder_.addAllMessages(other.corporateActionSources_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object reqId_ = "";
    /**
     * <code>string reqId = 1;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder setReqId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder clearReqId() {
      
      reqId_ = getDefaultInstance().getReqId();
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder setReqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reqId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource> corporateActionSources_ =
      java.util.Collections.emptyList();
    private void ensureCorporateActionSourcesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        corporateActionSources_ = new java.util.ArrayList<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource>(corporateActionSources_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourceOrBuilder> corporateActionSourcesBuilder_;

    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource> getCorporateActionSourcesList() {
      if (corporateActionSourcesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(corporateActionSources_);
      } else {
        return corporateActionSourcesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public int getCorporateActionSourcesCount() {
      if (corporateActionSourcesBuilder_ == null) {
        return corporateActionSources_.size();
      } else {
        return corporateActionSourcesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource getCorporateActionSources(int index) {
      if (corporateActionSourcesBuilder_ == null) {
        return corporateActionSources_.get(index);
      } else {
        return corporateActionSourcesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder setCorporateActionSources(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource value) {
      if (corporateActionSourcesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCorporateActionSourcesIsMutable();
        corporateActionSources_.set(index, value);
        onChanged();
      } else {
        corporateActionSourcesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder setCorporateActionSources(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder builderForValue) {
      if (corporateActionSourcesBuilder_ == null) {
        ensureCorporateActionSourcesIsMutable();
        corporateActionSources_.set(index, builderForValue.build());
        onChanged();
      } else {
        corporateActionSourcesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder addCorporateActionSources(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource value) {
      if (corporateActionSourcesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCorporateActionSourcesIsMutable();
        corporateActionSources_.add(value);
        onChanged();
      } else {
        corporateActionSourcesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder addCorporateActionSources(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource value) {
      if (corporateActionSourcesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCorporateActionSourcesIsMutable();
        corporateActionSources_.add(index, value);
        onChanged();
      } else {
        corporateActionSourcesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder addCorporateActionSources(
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder builderForValue) {
      if (corporateActionSourcesBuilder_ == null) {
        ensureCorporateActionSourcesIsMutable();
        corporateActionSources_.add(builderForValue.build());
        onChanged();
      } else {
        corporateActionSourcesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder addCorporateActionSources(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder builderForValue) {
      if (corporateActionSourcesBuilder_ == null) {
        ensureCorporateActionSourcesIsMutable();
        corporateActionSources_.add(index, builderForValue.build());
        onChanged();
      } else {
        corporateActionSourcesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder addAllCorporateActionSources(
        java.lang.Iterable<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource> values) {
      if (corporateActionSourcesBuilder_ == null) {
        ensureCorporateActionSourcesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, corporateActionSources_);
        onChanged();
      } else {
        corporateActionSourcesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder clearCorporateActionSources() {
      if (corporateActionSourcesBuilder_ == null) {
        corporateActionSources_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        corporateActionSourcesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public Builder removeCorporateActionSources(int index) {
      if (corporateActionSourcesBuilder_ == null) {
        ensureCorporateActionSourcesIsMutable();
        corporateActionSources_.remove(index);
        onChanged();
      } else {
        corporateActionSourcesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder getCorporateActionSourcesBuilder(
        int index) {
      return getCorporateActionSourcesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourceOrBuilder getCorporateActionSourcesOrBuilder(
        int index) {
      if (corporateActionSourcesBuilder_ == null) {
        return corporateActionSources_.get(index);  } else {
        return corporateActionSourcesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourceOrBuilder> 
         getCorporateActionSourcesOrBuilderList() {
      if (corporateActionSourcesBuilder_ != null) {
        return corporateActionSourcesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(corporateActionSources_);
      }
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder addCorporateActionSourcesBuilder() {
      return getCorporateActionSourcesFieldBuilder().addBuilder(
          com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.getDefaultInstance());
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder addCorporateActionSourcesBuilder(
        int index) {
      return getCorporateActionSourcesFieldBuilder().addBuilder(
          index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.getDefaultInstance());
    }
    /**
     * <code>repeated .CorporateActionSource corporateActionSources = 2;</code>
     */
    public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder> 
         getCorporateActionSourcesBuilderList() {
      return getCorporateActionSourcesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourceOrBuilder> 
        getCorporateActionSourcesFieldBuilder() {
      if (corporateActionSourcesBuilder_ == null) {
        corporateActionSourcesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSource.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourceOrBuilder>(
                corporateActionSources_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        corporateActionSources_ = null;
      }
      return corporateActionSourcesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CorporateActionSourcesResponse)
  }

  // @@protoc_insertion_point(class_scope:CorporateActionSourcesResponse)
  private static final com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse();
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CorporateActionSourcesResponse>
      PARSER = new com.google.protobuf.AbstractParser<CorporateActionSourcesResponse>() {
    @java.lang.Override
    public CorporateActionSourcesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CorporateActionSourcesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CorporateActionSourcesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CorporateActionSourcesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionSourcesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

