// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface CorporateActionKindGroupsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CorporateActionKindGroupsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   */
  java.lang.String getReqId();
  /**
   * <code>string reqId = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>repeated .CorporateActionKindGroups corporateActionKindGroups = 2;</code>
   */
  java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKindGroups> 
      getCorporateActionKindGroupsList();
  /**
   * <code>repeated .CorporateActionKindGroups corporateActionKindGroups = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKindGroups getCorporateActionKindGroups(int index);
  /**
   * <code>repeated .CorporateActionKindGroups corporateActionKindGroups = 2;</code>
   */
  int getCorporateActionKindGroupsCount();
  /**
   * <code>repeated .CorporateActionKindGroups corporateActionKindGroups = 2;</code>
   */
  java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKindGroupsOrBuilder> 
      getCorporateActionKindGroupsOrBuilderList();
  /**
   * <code>repeated .CorporateActionKindGroups corporateActionKindGroups = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionKindGroupsOrBuilder getCorporateActionKindGroupsOrBuilder(
      int index);
}
