// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface CorporateActionActionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CorporateActionActionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   */
  java.lang.String getReqId();
  /**
   * <code>string reqId = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>repeated .CorporateActionActions corporateActionActions = 2;</code>
   */
  java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionActions> 
      getCorporateActionActionsList();
  /**
   * <code>repeated .CorporateActionActions corporateActionActions = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionActions getCorporateActionActions(int index);
  /**
   * <code>repeated .CorporateActionActions corporateActionActions = 2;</code>
   */
  int getCorporateActionActionsCount();
  /**
   * <code>repeated .CorporateActionActions corporateActionActions = 2;</code>
   */
  java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionActionsOrBuilder> 
      getCorporateActionActionsOrBuilderList();
  /**
   * <code>repeated .CorporateActionActions corporateActionActions = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.CorporateActionActionsOrBuilder getCorporateActionActionsOrBuilder(
      int index);
}
