// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface EmitentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Emitent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fininstid = 1;</code>
   */
  long getFininstid();

  /**
   * <code>string shortname_rus = 2;</code>
   */
  java.lang.String getShortnameRus();
  /**
   * <code>string shortname_rus = 2;</code>
   */
  com.google.protobuf.ByteString
      getShortnameRusBytes();

  /**
   * <code>string shortname_eng = 3;</code>
   */
  java.lang.String getShortnameEng();
  /**
   * <code>string shortname_eng = 3;</code>
   */
  com.google.protobuf.ByteString
      getShortnameEngBytes();

  /**
   * <code>string inn = 4;</code>
   */
  java.lang.String getInn();
  /**
   * <code>string inn = 4;</code>
   */
  com.google.protobuf.ByteString
      getInnBytes();

  /**
   * <code>string okpo = 5;</code>
   */
  java.lang.String getOkpo();
  /**
   * <code>string okpo = 5;</code>
   */
  com.google.protobuf.ByteString
      getOkpoBytes();

  /**
   * <code>string ogrn = 6;</code>
   */
  java.lang.String getOgrn();
  /**
   * <code>string ogrn = 6;</code>
   */
  com.google.protobuf.ByteString
      getOgrnBytes();

  /**
   * <code>string code = 7;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 7;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string sector = 8;</code>
   */
  java.lang.String getSector();
  /**
   * <code>string sector = 8;</code>
   */
  com.google.protobuf.ByteString
      getSectorBytes();

  /**
   * <code>string legal_address = 9;</code>
   */
  java.lang.String getLegalAddress();
  /**
   * <code>string legal_address = 9;</code>
   */
  com.google.protobuf.ByteString
      getLegalAddressBytes();

  /**
   * <code>string phone = 10;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 10;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();

  /**
   * <code>string www = 11;</code>
   */
  java.lang.String getWww();
  /**
   * <code>string www = 11;</code>
   */
  com.google.protobuf.ByteString
      getWwwBytes();

  /**
   * <code>int64 update_date = 12;</code>
   */
  long getUpdateDate();

  /**
   * <code>string fullname_rus_nrd = 13;</code>
   */
  java.lang.String getFullnameRusNrd();
  /**
   * <code>string fullname_rus_nrd = 13;</code>
   */
  com.google.protobuf.ByteString
      getFullnameRusNrdBytes();

  /**
   * <code>string fullname_eng_nrd = 14;</code>
   */
  java.lang.String getFullnameEngNrd();
  /**
   * <code>string fullname_eng_nrd = 14;</code>
   */
  com.google.protobuf.ByteString
      getFullnameEngNrdBytes();

  /**
   * <code>string shortname_rus_nrd = 15;</code>
   */
  java.lang.String getShortnameRusNrd();
  /**
   * <code>string shortname_rus_nrd = 15;</code>
   */
  com.google.protobuf.ByteString
      getShortnameRusNrdBytes();

  /**
   * <code>string shortname_eng_nrd = 16;</code>
   */
  java.lang.String getShortnameEngNrd();
  /**
   * <code>string shortname_eng_nrd = 16;</code>
   */
  com.google.protobuf.ByteString
      getShortnameEngNrdBytes();

  /**
   * <code>string company_type_short_name = 17;</code>
   */
  java.lang.String getCompanyTypeShortName();
  /**
   * <code>string company_type_short_name = 17;</code>
   */
  com.google.protobuf.ByteString
      getCompanyTypeShortNameBytes();

  /**
   * <code>string state_reg_num = 18;</code>
   */
  java.lang.String getStateRegNum();
  /**
   * <code>string state_reg_num = 18;</code>
   */
  com.google.protobuf.ByteString
      getStateRegNumBytes();

  /**
   * <code>.google.protobuf.Int64Value state_reg_date = 19;</code>
   */
  boolean hasStateRegDate();
  /**
   * <code>.google.protobuf.Int64Value state_reg_date = 19;</code>
   */
  com.google.protobuf.Int64Value getStateRegDate();
  /**
   * <code>.google.protobuf.Int64Value state_reg_date = 19;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getStateRegDateOrBuilder();

  /**
   * <code>string state_reg_name = 20;</code>
   */
  java.lang.String getStateRegName();
  /**
   * <code>string state_reg_name = 20;</code>
   */
  com.google.protobuf.ByteString
      getStateRegNameBytes();

  /**
   * <code>.google.protobuf.Int64Value egrul_date = 21;</code>
   */
  boolean hasEgrulDate();
  /**
   * <code>.google.protobuf.Int64Value egrul_date = 21;</code>
   */
  com.google.protobuf.Int64Value getEgrulDate();
  /**
   * <code>.google.protobuf.Int64Value egrul_date = 21;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getEgrulDateOrBuilder();

  /**
   * <code>string egrul_organ_name = 22;</code>
   */
  java.lang.String getEgrulOrganName();
  /**
   * <code>string egrul_organ_name = 22;</code>
   */
  com.google.protobuf.ByteString
      getEgrulOrganNameBytes();

  /**
   * <code>string country = 23;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 23;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>string lei_code = 24;</code>
   */
  java.lang.String getLeiCode();
  /**
   * <code>string lei_code = 24;</code>
   */
  com.google.protobuf.ByteString
      getLeiCodeBytes();

  /**
   * <code>string bik = 25;</code>
   */
  java.lang.String getBik();
  /**
   * <code>string bik = 25;</code>
   */
  com.google.protobuf.ByteString
      getBikBytes();

  /**
   * <code>string fax = 26;</code>
   */
  java.lang.String getFax();
  /**
   * <code>string fax = 26;</code>
   */
  com.google.protobuf.ByteString
      getFaxBytes();

  /**
   * <code>string e_mail = 27;</code>
   */
  java.lang.String getEMail();
  /**
   * <code>string e_mail = 27;</code>
   */
  com.google.protobuf.ByteString
      getEMailBytes();

  /**
   * <code>string credit_cmp = 28;</code>
   */
  java.lang.String getCreditCmp();
  /**
   * <code>string credit_cmp = 28;</code>
   */
  com.google.protobuf.ByteString
      getCreditCmpBytes();

  /**
   * <code>string is_bank_4_non_resident = 29;</code>
   */
  java.lang.String getIsBank4NonResident();
  /**
   * <code>string is_bank_4_non_resident = 29;</code>
   */
  com.google.protobuf.ByteString
      getIsBank4NonResidentBytes();

  /**
   * <code>string swift = 30;</code>
   */
  java.lang.String getSwift();
  /**
   * <code>string swift = 30;</code>
   */
  com.google.protobuf.ByteString
      getSwiftBytes();

  /**
   * <code>.google.protobuf.Int32Value country_oksm = 31;</code>
   */
  boolean hasCountryOksm();
  /**
   * <code>.google.protobuf.Int32Value country_oksm = 31;</code>
   */
  com.google.protobuf.Int32Value getCountryOksm();
  /**
   * <code>.google.protobuf.Int32Value country_oksm = 31;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getCountryOksmOrBuilder();

  /**
   * <code>string country_name_rus = 32;</code>
   */
  java.lang.String getCountryNameRus();
  /**
   * <code>string country_name_rus = 32;</code>
   */
  com.google.protobuf.ByteString
      getCountryNameRusBytes();

  /**
   * <code>string country_name_eng = 33;</code>
   */
  java.lang.String getCountryNameEng();
  /**
   * <code>string country_name_eng = 33;</code>
   */
  com.google.protobuf.ByteString
      getCountryNameEngBytes();

  /**
   * <code>string region_inn = 34;</code>
   */
  java.lang.String getRegionInn();
  /**
   * <code>string region_inn = 34;</code>
   */
  com.google.protobuf.ByteString
      getRegionInnBytes();

  /**
   * <code>string region_soato = 35;</code>
   */
  java.lang.String getRegionSoato();
  /**
   * <code>string region_soato = 35;</code>
   */
  com.google.protobuf.ByteString
      getRegionSoatoBytes();

  /**
   * <code>string region_name = 36;</code>
   */
  java.lang.String getRegionName();
  /**
   * <code>string region_name = 36;</code>
   */
  com.google.protobuf.ByteString
      getRegionNameBytes();

  /**
   * <code>string fullname_rus = 37;</code>
   */
  java.lang.String getFullnameRus();
  /**
   * <code>string fullname_rus = 37;</code>
   */
  com.google.protobuf.ByteString
      getFullnameRusBytes();

  /**
   * <code>.google.protobuf.Int64Value sparkid = 38;</code>
   */
  boolean hasSparkid();
  /**
   * <code>.google.protobuf.Int64Value sparkid = 38;</code>
   */
  com.google.protobuf.Int64Value getSparkid();
  /**
   * <code>.google.protobuf.Int64Value sparkid = 38;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getSparkidOrBuilder();

  /**
   * <code>string br_fcsm_reg_code = 39;</code>
   */
  java.lang.String getBrFcsmRegCode();
  /**
   * <code>string br_fcsm_reg_code = 39;</code>
   */
  com.google.protobuf.ByteString
      getBrFcsmRegCodeBytes();

  /**
   * <code>.google.protobuf.DoubleValue capital = 40;</code>
   */
  boolean hasCapital();
  /**
   * <code>.google.protobuf.DoubleValue capital = 40;</code>
   */
  com.google.protobuf.DoubleValue getCapital();
  /**
   * <code>.google.protobuf.DoubleValue capital = 40;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getCapitalOrBuilder();

  /**
   * <code>string capital_unit = 41;</code>
   */
  java.lang.String getCapitalUnit();
  /**
   * <code>string capital_unit = 41;</code>
   */
  com.google.protobuf.ByteString
      getCapitalUnitBytes();

  /**
   * <code>string okved = 42;</code>
   */
  java.lang.String getOkved();
  /**
   * <code>string okved = 42;</code>
   */
  com.google.protobuf.ByteString
      getOkvedBytes();

  /**
   * <code>string oecd_lvl = 43;</code>
   */
  java.lang.String getOecdLvl();
  /**
   * <code>string oecd_lvl = 43;</code>
   */
  com.google.protobuf.ByteString
      getOecdLvlBytes();

  /**
   * <code>string oktmo = 44;</code>
   */
  java.lang.String getOktmo();
  /**
   * <code>string oktmo = 44;</code>
   */
  com.google.protobuf.ByteString
      getOktmoBytes();

  /**
   * <code>string okato = 45;</code>
   */
  java.lang.String getOkato();
  /**
   * <code>string okato = 45;</code>
   */
  com.google.protobuf.ByteString
      getOkatoBytes();

  /**
   * <code>string post_address = 46;</code>
   */
  java.lang.String getPostAddress();
  /**
   * <code>string post_address = 46;</code>
   */
  com.google.protobuf.ByteString
      getPostAddressBytes();

  /**
   * <code>string okopf = 47;</code>
   */
  java.lang.String getOkopf();
  /**
   * <code>string okopf = 47;</code>
   */
  com.google.protobuf.ByteString
      getOkopfBytes();

  /**
   * <code>string okogu = 48;</code>
   */
  java.lang.String getOkogu();
  /**
   * <code>string okogu = 48;</code>
   */
  com.google.protobuf.ByteString
      getOkoguBytes();

  /**
   * <code>.google.protobuf.Int32Value have_rating = 49;</code>
   */
  boolean hasHaveRating();
  /**
   * <code>.google.protobuf.Int32Value have_rating = 49;</code>
   */
  com.google.protobuf.Int32Value getHaveRating();
  /**
   * <code>.google.protobuf.Int32Value have_rating = 49;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getHaveRatingOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value have_risk = 50;</code>
   */
  boolean hasHaveRisk();
  /**
   * <code>.google.protobuf.Int32Value have_risk = 50;</code>
   */
  com.google.protobuf.Int32Value getHaveRisk();
  /**
   * <code>.google.protobuf.Int32Value have_risk = 50;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getHaveRiskOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value is_finorg = 51;</code>
   */
  boolean hasIsFinorg();
  /**
   * <code>.google.protobuf.Int32Value is_finorg = 51;</code>
   */
  com.google.protobuf.Int32Value getIsFinorg();
  /**
   * <code>.google.protobuf.Int32Value is_finorg = 51;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIsFinorgOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value is_control_by_finorg = 52;</code>
   */
  boolean hasIsControlByFinorg();
  /**
   * <code>.google.protobuf.Int32Value is_control_by_finorg = 52;</code>
   */
  com.google.protobuf.Int32Value getIsControlByFinorg();
  /**
   * <code>.google.protobuf.Int32Value is_control_by_finorg = 52;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIsControlByFinorgOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value is_gov_or_cb = 53;</code>
   */
  boolean hasIsGovOrCb();
  /**
   * <code>.google.protobuf.Int32Value is_gov_or_cb = 53;</code>
   */
  com.google.protobuf.Int32Value getIsGovOrCb();
  /**
   * <code>.google.protobuf.Int32Value is_gov_or_cb = 53;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIsGovOrCbOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value on_behalf_of_state = 54;</code>
   */
  boolean hasOnBehalfOfState();
  /**
   * <code>.google.protobuf.Int32Value on_behalf_of_state = 54;</code>
   */
  com.google.protobuf.Int32Value getOnBehalfOfState();
  /**
   * <code>.google.protobuf.Int32Value on_behalf_of_state = 54;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getOnBehalfOfStateOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value is_subjectrf = 55;</code>
   */
  boolean hasIsSubjectrf();
  /**
   * <code>.google.protobuf.Int32Value is_subjectrf = 55;</code>
   */
  com.google.protobuf.Int32Value getIsSubjectrf();
  /**
   * <code>.google.protobuf.Int32Value is_subjectrf = 55;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIsSubjectrfOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value is_cis_reg = 56;</code>
   */
  boolean hasIsCisReg();
  /**
   * <code>.google.protobuf.Int32Value is_cis_reg = 56;</code>
   */
  com.google.protobuf.Int32Value getIsCisReg();
  /**
   * <code>.google.protobuf.Int32Value is_cis_reg = 56;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIsCisRegOrBuilder();

  /**
   * <code>string issuer_nrd = 57;</code>
   */
  java.lang.String getIssuerNrd();
  /**
   * <code>string issuer_nrd = 57;</code>
   */
  com.google.protobuf.ByteString
      getIssuerNrdBytes();

  /**
   * <code>string tin = 58;</code>
   */
  java.lang.String getTin();
  /**
   * <code>string tin = 58;</code>
   */
  com.google.protobuf.ByteString
      getTinBytes();

  /**
   * <code>string kpp = 59;</code>
   */
  java.lang.String getKpp();
  /**
   * <code>string kpp = 59;</code>
   */
  com.google.protobuf.ByteString
      getKppBytes();

  /**
   * <code>string state_reg_number = 60;</code>
   */
  java.lang.String getStateRegNumber();
  /**
   * <code>string state_reg_number = 60;</code>
   */
  com.google.protobuf.ByteString
      getStateRegNumberBytes();

  /**
   * <code>.google.protobuf.Int64Value market_id_nrd = 61;</code>
   */
  boolean hasMarketIdNrd();
  /**
   * <code>.google.protobuf.Int64Value market_id_nrd = 61;</code>
   */
  com.google.protobuf.Int64Value getMarketIdNrd();
  /**
   * <code>.google.protobuf.Int64Value market_id_nrd = 61;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getMarketIdNrdOrBuilder();

  /**
   * <code>string market_name_rus_nrd = 62;</code>
   */
  java.lang.String getMarketNameRusNrd();
  /**
   * <code>string market_name_rus_nrd = 62;</code>
   */
  com.google.protobuf.ByteString
      getMarketNameRusNrdBytes();

  /**
   * <code>string market_name_eng_nrd = 63;</code>
   */
  java.lang.String getMarketNameEngNrd();
  /**
   * <code>string market_name_eng_nrd = 63;</code>
   */
  com.google.protobuf.ByteString
      getMarketNameEngNrdBytes();

  /**
   * <code>string sp_rx_entity_id = 64;</code>
   */
  java.lang.String getSpRxEntityId();
  /**
   * <code>string sp_rx_entity_id = 64;</code>
   */
  com.google.protobuf.ByteString
      getSpRxEntityIdBytes();

  /**
   * <code>string sp_shortname = 65;</code>
   */
  java.lang.String getSpShortname();
  /**
   * <code>string sp_shortname = 65;</code>
   */
  com.google.protobuf.ByteString
      getSpShortnameBytes();

  /**
   * <code>string mds_shortname = 66;</code>
   */
  java.lang.String getMdsShortname();
  /**
   * <code>string mds_shortname = 66;</code>
   */
  com.google.protobuf.ByteString
      getMdsShortnameBytes();

  /**
   * <code>string mds_org_id = 67;</code>
   */
  java.lang.String getMdsOrgId();
  /**
   * <code>string mds_org_id = 67;</code>
   */
  com.google.protobuf.ByteString
      getMdsOrgIdBytes();

  /**
   * <code>string fch_id = 68;</code>
   */
  java.lang.String getFchId();
  /**
   * <code>string fch_id = 68;</code>
   */
  com.google.protobuf.ByteString
      getFchIdBytes();

  /**
   * <code>string fch_shortname = 69;</code>
   */
  java.lang.String getFchShortname();
  /**
   * <code>string fch_shortname = 69;</code>
   */
  com.google.protobuf.ByteString
      getFchShortnameBytes();

  /**
   * <code>.google.protobuf.Int32Value is_monopoly = 70;</code>
   */
  boolean hasIsMonopoly();
  /**
   * <code>.google.protobuf.Int32Value is_monopoly = 70;</code>
   */
  com.google.protobuf.Int32Value getIsMonopoly();
  /**
   * <code>.google.protobuf.Int32Value is_monopoly = 70;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIsMonopolyOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value is_strategic = 71;</code>
   */
  boolean hasIsStrategic();
  /**
   * <code>.google.protobuf.Int32Value is_strategic = 71;</code>
   */
  com.google.protobuf.Int32Value getIsStrategic();
  /**
   * <code>.google.protobuf.Int32Value is_strategic = 71;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIsStrategicOrBuilder();

  /**
   * <code>string ifo_list = 72;</code>
   */
  java.lang.String getIfoList();
  /**
   * <code>string ifo_list = 72;</code>
   */
  com.google.protobuf.ByteString
      getIfoListBytes();

  /**
   * <code>.google.protobuf.DoubleValue isregion = 73;</code>
   */
  boolean hasIsregion();
  /**
   * <code>.google.protobuf.DoubleValue isregion = 73;</code>
   */
  com.google.protobuf.DoubleValue getIsregion();
  /**
   * <code>.google.protobuf.DoubleValue isregion = 73;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getIsregionOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value id_emitent = 74;</code>
   */
  boolean hasIdEmitent();
  /**
   * <code>.google.protobuf.Int64Value id_emitent = 74;</code>
   */
  com.google.protobuf.Int64Value getIdEmitent();
  /**
   * <code>.google.protobuf.Int64Value id_emitent = 74;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdEmitentOrBuilder();

  /**
   * <code>string sic = 75;</code>
   */
  java.lang.String getSic();
  /**
   * <code>string sic = 75;</code>
   */
  com.google.protobuf.ByteString
      getSicBytes();

  /**
   * <code>string sector4212u = 76;</code>
   */
  java.lang.String getSector4212U();
  /**
   * <code>string sector4212u = 76;</code>
   */
  com.google.protobuf.ByteString
      getSector4212UBytes();

  /**
   * <code>string sna2008 = 77;</code>
   */
  java.lang.String getSna2008();
  /**
   * <code>string sna2008 = 77;</code>
   */
  com.google.protobuf.ByteString
      getSna2008Bytes();
}
