// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface InfoCurrenciesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoCurrenciesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   */
  java.lang.String getReqId();
  /**
   * <code>string reqId = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>repeated .InfoCurrencies infoCurrencies = 2;</code>
   */
  java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoCurrencies> 
      getInfoCurrenciesList();
  /**
   * <code>repeated .InfoCurrencies infoCurrencies = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoCurrencies getInfoCurrencies(int index);
  /**
   * <code>repeated .InfoCurrencies infoCurrencies = 2;</code>
   */
  int getInfoCurrenciesCount();
  /**
   * <code>repeated .InfoCurrencies infoCurrencies = 2;</code>
   */
  java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoCurrenciesOrBuilder> 
      getInfoCurrenciesOrBuilderList();
  /**
   * <code>repeated .InfoCurrencies infoCurrencies = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoCurrenciesOrBuilder getInfoCurrenciesOrBuilder(
      int index);
}
