// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface InfoSecuritiesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:InfoSecuritiesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   */
  java.lang.String getReqId();
  /**
   * <code>string reqId = 1;</code>
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>repeated .Security securities = 2;</code>
   */
  java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Security> 
      getSecuritiesList();
  /**
   * <code>repeated .Security securities = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Security getSecurities(int index);
  /**
   * <code>repeated .Security securities = 2;</code>
   */
  int getSecuritiesCount();
  /**
   * <code>repeated .Security securities = 2;</code>
   */
  java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.SecurityOrBuilder> 
      getSecuritiesOrBuilderList();
  /**
   * <code>repeated .Security securities = 2;</code>
   */
  com.bcs.bm.catalog_of_instruments_rudata.client.grpc.SecurityOrBuilder getSecuritiesOrBuilder(
      int index);
}
