// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

/**
 * Protobuf type {@code InfoEmitentsResponse}
 */
public  final class InfoEmitentsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:InfoEmitentsResponse)
    InfoEmitentsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoEmitentsResponse.newBuilder() to construct.
  private InfoEmitentsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoEmitentsResponse() {
    reqId_ = "";
    emitents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InfoEmitentsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InfoEmitentsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reqId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              emitents_ = new java.util.ArrayList<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent>();
              mutable_bitField0_ |= 0x00000001;
            }
            emitents_.add(
                input.readMessage(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        emitents_ = java.util.Collections.unmodifiableList(emitents_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_InfoEmitentsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_InfoEmitentsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse.Builder.class);
  }

  public static final int REQID_FIELD_NUMBER = 1;
  private volatile java.lang.Object reqId_;
  /**
   * <code>string reqId = 1;</code>
   */
  public java.lang.String getReqId() {
    java.lang.Object ref = reqId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reqId_ = s;
      return s;
    }
  }
  /**
   * <code>string reqId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReqIdBytes() {
    java.lang.Object ref = reqId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMITENTS_FIELD_NUMBER = 2;
  private java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent> emitents_;
  /**
   * <code>repeated .Emitent emitents = 2;</code>
   */
  public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent> getEmitentsList() {
    return emitents_;
  }
  /**
   * <code>repeated .Emitent emitents = 2;</code>
   */
  public java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.EmitentOrBuilder> 
      getEmitentsOrBuilderList() {
    return emitents_;
  }
  /**
   * <code>repeated .Emitent emitents = 2;</code>
   */
  public int getEmitentsCount() {
    return emitents_.size();
  }
  /**
   * <code>repeated .Emitent emitents = 2;</code>
   */
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent getEmitents(int index) {
    return emitents_.get(index);
  }
  /**
   * <code>repeated .Emitent emitents = 2;</code>
   */
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.EmitentOrBuilder getEmitentsOrBuilder(
      int index) {
    return emitents_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReqIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqId_);
    }
    for (int i = 0; i < emitents_.size(); i++) {
      output.writeMessage(2, emitents_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReqIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqId_);
    }
    for (int i = 0; i < emitents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, emitents_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse)) {
      return super.equals(obj);
    }
    com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse other = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse) obj;

    if (!getReqId()
        .equals(other.getReqId())) return false;
    if (!getEmitentsList()
        .equals(other.getEmitentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + getReqId().hashCode();
    if (getEmitentsCount() > 0) {
      hash = (37 * hash) + EMITENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEmitentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code InfoEmitentsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:InfoEmitentsResponse)
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_InfoEmitentsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_InfoEmitentsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse.Builder.class);
    }

    // Construct using com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmitentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reqId_ = "";

      if (emitentsBuilder_ == null) {
        emitents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        emitentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_InfoEmitentsResponse_descriptor;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse getDefaultInstanceForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse build() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse buildPartial() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse result = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse(this);
      int from_bitField0_ = bitField0_;
      result.reqId_ = reqId_;
      if (emitentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          emitents_ = java.util.Collections.unmodifiableList(emitents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.emitents_ = emitents_;
      } else {
        result.emitents_ = emitentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse) {
        return mergeFrom((com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse other) {
      if (other == com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse.getDefaultInstance()) return this;
      if (!other.getReqId().isEmpty()) {
        reqId_ = other.reqId_;
        onChanged();
      }
      if (emitentsBuilder_ == null) {
        if (!other.emitents_.isEmpty()) {
          if (emitents_.isEmpty()) {
            emitents_ = other.emitents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmitentsIsMutable();
            emitents_.addAll(other.emitents_);
          }
          onChanged();
        }
      } else {
        if (!other.emitents_.isEmpty()) {
          if (emitentsBuilder_.isEmpty()) {
            emitentsBuilder_.dispose();
            emitentsBuilder_ = null;
            emitents_ = other.emitents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            emitentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmitentsFieldBuilder() : null;
          } else {
            emitentsBuilder_.addAllMessages(other.emitents_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object reqId_ = "";
    /**
     * <code>string reqId = 1;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder setReqId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder clearReqId() {
      
      reqId_ = getDefaultInstance().getReqId();
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder setReqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reqId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent> emitents_ =
      java.util.Collections.emptyList();
    private void ensureEmitentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        emitents_ = new java.util.ArrayList<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent>(emitents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.EmitentOrBuilder> emitentsBuilder_;

    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent> getEmitentsList() {
      if (emitentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(emitents_);
      } else {
        return emitentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public int getEmitentsCount() {
      if (emitentsBuilder_ == null) {
        return emitents_.size();
      } else {
        return emitentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent getEmitents(int index) {
      if (emitentsBuilder_ == null) {
        return emitents_.get(index);
      } else {
        return emitentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder setEmitents(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent value) {
      if (emitentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmitentsIsMutable();
        emitents_.set(index, value);
        onChanged();
      } else {
        emitentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder setEmitents(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder builderForValue) {
      if (emitentsBuilder_ == null) {
        ensureEmitentsIsMutable();
        emitents_.set(index, builderForValue.build());
        onChanged();
      } else {
        emitentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder addEmitents(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent value) {
      if (emitentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmitentsIsMutable();
        emitents_.add(value);
        onChanged();
      } else {
        emitentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder addEmitents(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent value) {
      if (emitentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmitentsIsMutable();
        emitents_.add(index, value);
        onChanged();
      } else {
        emitentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder addEmitents(
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder builderForValue) {
      if (emitentsBuilder_ == null) {
        ensureEmitentsIsMutable();
        emitents_.add(builderForValue.build());
        onChanged();
      } else {
        emitentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder addEmitents(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder builderForValue) {
      if (emitentsBuilder_ == null) {
        ensureEmitentsIsMutable();
        emitents_.add(index, builderForValue.build());
        onChanged();
      } else {
        emitentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder addAllEmitents(
        java.lang.Iterable<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent> values) {
      if (emitentsBuilder_ == null) {
        ensureEmitentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emitents_);
        onChanged();
      } else {
        emitentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder clearEmitents() {
      if (emitentsBuilder_ == null) {
        emitents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        emitentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public Builder removeEmitents(int index) {
      if (emitentsBuilder_ == null) {
        ensureEmitentsIsMutable();
        emitents_.remove(index);
        onChanged();
      } else {
        emitentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder getEmitentsBuilder(
        int index) {
      return getEmitentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.EmitentOrBuilder getEmitentsOrBuilder(
        int index) {
      if (emitentsBuilder_ == null) {
        return emitents_.get(index);  } else {
        return emitentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.EmitentOrBuilder> 
         getEmitentsOrBuilderList() {
      if (emitentsBuilder_ != null) {
        return emitentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(emitents_);
      }
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder addEmitentsBuilder() {
      return getEmitentsFieldBuilder().addBuilder(
          com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.getDefaultInstance());
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder addEmitentsBuilder(
        int index) {
      return getEmitentsFieldBuilder().addBuilder(
          index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.getDefaultInstance());
    }
    /**
     * <code>repeated .Emitent emitents = 2;</code>
     */
    public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder> 
         getEmitentsBuilderList() {
      return getEmitentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.EmitentOrBuilder> 
        getEmitentsFieldBuilder() {
      if (emitentsBuilder_ == null) {
        emitentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.Emitent.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.EmitentOrBuilder>(
                emitents_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        emitents_ = null;
      }
      return emitentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:InfoEmitentsResponse)
  }

  // @@protoc_insertion_point(class_scope:InfoEmitentsResponse)
  private static final com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse();
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoEmitentsResponse>
      PARSER = new com.google.protobuf.AbstractParser<InfoEmitentsResponse>() {
    @java.lang.Override
    public InfoEmitentsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InfoEmitentsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InfoEmitentsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoEmitentsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.InfoEmitentsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

