// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface Int64KeysOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Int64Keys)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .google.protobuf.Int64Value&gt; keys = 1;</code>
   */
  int getKeysCount();
  /**
   * <code>map&lt;string, .google.protobuf.Int64Value&gt; keys = 1;</code>
   */
  boolean containsKeys(
      java.lang.String key);
  /**
   * Use {@link #getKeysMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.Int64Value>
  getKeys();
  /**
   * <code>map&lt;string, .google.protobuf.Int64Value&gt; keys = 1;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.Int64Value>
  getKeysMap();
  /**
   * <code>map&lt;string, .google.protobuf.Int64Value&gt; keys = 1;</code>
   */

  com.google.protobuf.Int64Value getKeysOrDefault(
      java.lang.String key,
      com.google.protobuf.Int64Value defaultValue);
  /**
   * <code>map&lt;string, .google.protobuf.Int64Value&gt; keys = 1;</code>
   */

  com.google.protobuf.Int64Value getKeysOrThrow(
      java.lang.String key);
}
