// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface SecurityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Security)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fintoolid = 1;</code>
   */
  long getFintoolid();

  /**
   * <code>int64 idFintool = 2;</code>
   */
  long getIdFintool();

  /**
   * <code>.google.protobuf.Int64Value fininstid = 3;</code>
   */
  boolean hasFininstid();
  /**
   * <code>.google.protobuf.Int64Value fininstid = 3;</code>
   */
  com.google.protobuf.Int64Value getFininstid();
  /**
   * <code>.google.protobuf.Int64Value fininstid = 3;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getFininstidOrBuilder();

  /**
   * <code>int64 updateDate = 4;</code>
   */
  long getUpdateDate();

  /**
   * <code>.google.protobuf.Int64Value importTime = 5;</code>
   */
  boolean hasImportTime();
  /**
   * <code>.google.protobuf.Int64Value importTime = 5;</code>
   */
  com.google.protobuf.Int64Value getImportTime();
  /**
   * <code>.google.protobuf.Int64Value importTime = 5;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getImportTimeOrBuilder();

  /**
   * <code>string borrowerinn = 6;</code>
   */
  java.lang.String getBorrowerinn();
  /**
   * <code>string borrowerinn = 6;</code>
   */
  com.google.protobuf.ByteString
      getBorrowerinnBytes();

  /**
   * <code>string borrowername = 7;</code>
   */
  java.lang.String getBorrowername();
  /**
   * <code>string borrowername = 7;</code>
   */
  com.google.protobuf.ByteString
      getBorrowernameBytes();

  /**
   * <code>string borrowersector = 8;</code>
   */
  java.lang.String getBorrowersector();
  /**
   * <code>string borrowersector = 8;</code>
   */
  com.google.protobuf.ByteString
      getBorrowersectorBytes();

  /**
   * <code>.google.protobuf.Int64Value borroweruid = 9;</code>
   */
  boolean hasBorroweruid();
  /**
   * <code>.google.protobuf.Int64Value borroweruid = 9;</code>
   */
  com.google.protobuf.Int64Value getBorroweruid();
  /**
   * <code>.google.protobuf.Int64Value borroweruid = 9;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getBorroweruidOrBuilder();

  /**
   * <code>string cfi = 10;</code>
   */
  java.lang.String getCfi();
  /**
   * <code>string cfi = 10;</code>
   */
  com.google.protobuf.ByteString
      getCfiBytes();

  /**
   * <code>string couponRate = 11;</code>
   */
  java.lang.String getCouponRate();
  /**
   * <code>string couponRate = 11;</code>
   */
  com.google.protobuf.ByteString
      getCouponRateBytes();

  /**
   * <code>.google.protobuf.DoubleValue couponsPerYear = 12;</code>
   */
  boolean hasCouponsPerYear();
  /**
   * <code>.google.protobuf.DoubleValue couponsPerYear = 12;</code>
   */
  com.google.protobuf.DoubleValue getCouponsPerYear();
  /**
   * <code>.google.protobuf.DoubleValue couponsPerYear = 12;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getCouponsPerYearOrBuilder();

  /**
   * <code>string emitentShortnameRus = 13;</code>
   */
  java.lang.String getEmitentShortnameRus();
  /**
   * <code>string emitentShortnameRus = 13;</code>
   */
  com.google.protobuf.ByteString
      getEmitentShortnameRusBytes();

  /**
   * <code>.google.protobuf.Int64Value endmtyDate = 14;</code>
   */
  boolean hasEndmtyDate();
  /**
   * <code>.google.protobuf.Int64Value endmtyDate = 14;</code>
   */
  com.google.protobuf.Int64Value getEndmtyDate();
  /**
   * <code>.google.protobuf.Int64Value endmtyDate = 14;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getEndmtyDateOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue facevalue = 15;</code>
   */
  boolean hasFacevalue();
  /**
   * <code>.google.protobuf.DoubleValue facevalue = 15;</code>
   */
  com.google.protobuf.DoubleValue getFacevalue();
  /**
   * <code>.google.protobuf.DoubleValue facevalue = 15;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getFacevalueOrBuilder();

  /**
   * <code>string facevalueCurrency = 16;</code>
   */
  java.lang.String getFacevalueCurrency();
  /**
   * <code>string facevalueCurrency = 16;</code>
   */
  com.google.protobuf.ByteString
      getFacevalueCurrencyBytes();

  /**
   * <code>string fintooltype = 17;</code>
   */
  java.lang.String getFintooltype();
  /**
   * <code>string fintooltype = 17;</code>
   */
  com.google.protobuf.ByteString
      getFintooltypeBytes();

  /**
   * <code>string fullnameRus = 18;</code>
   */
  java.lang.String getFullnameRus();
  /**
   * <code>string fullnameRus = 18;</code>
   */
  com.google.protobuf.ByteString
      getFullnameRusBytes();

  /**
   * <code>string inn = 19;</code>
   */
  java.lang.String getInn();
  /**
   * <code>string inn = 19;</code>
   */
  com.google.protobuf.ByteString
      getInnBytes();

  /**
   * <code>string isin = 20;</code>
   */
  java.lang.String getIsin();
  /**
   * <code>string isin = 20;</code>
   */
  com.google.protobuf.ByteString
      getIsinBytes();

  /**
   * <code>.google.protobuf.DoubleValue issueVol = 21;</code>
   */
  boolean hasIssueVol();
  /**
   * <code>.google.protobuf.DoubleValue issueVol = 21;</code>
   */
  com.google.protobuf.DoubleValue getIssueVol();
  /**
   * <code>.google.protobuf.DoubleValue issueVol = 21;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getIssueVolOrBuilder();

  /**
   * <code>string nsdService = 22;</code>
   */
  java.lang.String getNsdService();
  /**
   * <code>string nsdService = 22;</code>
   */
  com.google.protobuf.ByteString
      getNsdServiceBytes();

  /**
   * <code>string ogrn = 23;</code>
   */
  java.lang.String getOgrn();
  /**
   * <code>string ogrn = 23;</code>
   */
  com.google.protobuf.ByteString
      getOgrnBytes();

  /**
   * <code>string okpo = 24;</code>
   */
  java.lang.String getOkpo();
  /**
   * <code>string okpo = 24;</code>
   */
  com.google.protobuf.ByteString
      getOkpoBytes();

  /**
   * <code>.google.protobuf.DoubleValue onQuatro = 25;</code>
   */
  boolean hasOnQuatro();
  /**
   * <code>.google.protobuf.DoubleValue onQuatro = 25;</code>
   */
  com.google.protobuf.DoubleValue getOnQuatro();
  /**
   * <code>.google.protobuf.DoubleValue onQuatro = 25;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getOnQuatroOrBuilder();

  /**
   * <code>string quatroId = 26;</code>
   */
  java.lang.String getQuatroId();
  /**
   * <code>string quatroId = 26;</code>
   */
  com.google.protobuf.ByteString
      getQuatroIdBytes();

  /**
   * <code>string regCode = 27;</code>
   */
  java.lang.String getRegCode();
  /**
   * <code>string regCode = 27;</code>
   */
  com.google.protobuf.ByteString
      getRegCodeBytes();

  /**
   * <code>string sector = 28;</code>
   */
  java.lang.String getSector();
  /**
   * <code>string sector = 28;</code>
   */
  com.google.protobuf.ByteString
      getSectorBytes();

  /**
   * <code>string securitykind = 29;</code>
   */
  java.lang.String getSecuritykind();
  /**
   * <code>string securitykind = 29;</code>
   */
  com.google.protobuf.ByteString
      getSecuritykindBytes();

  /**
   * <code>string securitytype = 30;</code>
   */
  java.lang.String getSecuritytype();
  /**
   * <code>string securitytype = 30;</code>
   */
  com.google.protobuf.ByteString
      getSecuritytypeBytes();

  /**
   * <code>string shortnameRus = 31;</code>
   */
  java.lang.String getShortnameRus();
  /**
   * <code>string shortnameRus = 31;</code>
   */
  com.google.protobuf.ByteString
      getShortnameRusBytes();

  /**
   * <code>string statusName = 32;</code>
   */
  java.lang.String getStatusName();
  /**
   * <code>string statusName = 32;</code>
   */
  com.google.protobuf.ByteString
      getStatusNameBytes();

  /**
   * <code>int32 subType = 33;</code>
   */
  int getSubType();

  /**
   * <code>int32 type = 34;</code>
   */
  int getType();

  /**
   * <code>.google.protobuf.Int64Value idemitent = 35;</code>
   */
  boolean hasIdemitent();
  /**
   * <code>.google.protobuf.Int64Value idemitent = 35;</code>
   */
  com.google.protobuf.Int64Value getIdemitent();
  /**
   * <code>.google.protobuf.Int64Value idemitent = 35;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdemitentOrBuilder();

  /**
   * <code>string nrdcode = 36;</code>
   */
  java.lang.String getNrdcode();
  /**
   * <code>string nrdcode = 36;</code>
   */
  com.google.protobuf.ByteString
      getNrdcodeBytes();

  /**
   * <code>string id_iss = 37;</code>
   */
  java.lang.String getIdIss();
  /**
   * <code>string id_iss = 37;</code>
   */
  com.google.protobuf.ByteString
      getIdIssBytes();
}
