// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface ShareDividendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShareDividend)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fintoolid = 1;</code>
   */
  long getFintoolid();

  /**
   * <code>string decision_date = 2;</code>
   */
  java.lang.String getDecisionDate();
  /**
   * <code>string decision_date = 2;</code>
   */
  com.google.protobuf.ByteString
      getDecisionDateBytes();

  /**
   * <code>string declared_pay_date = 3;</code>
   */
  java.lang.String getDeclaredPayDate();
  /**
   * <code>string declared_pay_date = 3;</code>
   */
  com.google.protobuf.ByteString
      getDeclaredPayDateBytes();

  /**
   * <code>string declared_pay_date_nominee = 4;</code>
   */
  java.lang.String getDeclaredPayDateNominee();
  /**
   * <code>string declared_pay_date_nominee = 4;</code>
   */
  com.google.protobuf.ByteString
      getDeclaredPayDateNomineeBytes();

  /**
   * <code>.google.protobuf.DoubleValue declared_sum_dividval = 5;</code>
   */
  boolean hasDeclaredSumDividval();
  /**
   * <code>.google.protobuf.DoubleValue declared_sum_dividval = 5;</code>
   */
  com.google.protobuf.DoubleValue getDeclaredSumDividval();
  /**
   * <code>.google.protobuf.DoubleValue declared_sum_dividval = 5;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDeclaredSumDividvalOrBuilder();

  /**
   * <code>int64 dev_organ = 6;</code>
   */
  long getDevOrgan();

  /**
   * <code>string list_date = 7;</code>
   */
  java.lang.String getListDate();
  /**
   * <code>string list_date = 7;</code>
   */
  com.google.protobuf.ByteString
      getListDateBytes();

  /**
   * <code>string list_dividend_date = 8;</code>
   */
  java.lang.String getListDividendDate();
  /**
   * <code>string list_dividend_date = 8;</code>
   */
  com.google.protobuf.ByteString
      getListDividendDateBytes();

  /**
   * <code>string note = 9;</code>
   */
  java.lang.String getNote();
  /**
   * <code>string note = 9;</code>
   */
  com.google.protobuf.ByteString
      getNoteBytes();

  /**
   * <code>string payed = 10;</code>
   */
  java.lang.String getPayed();
  /**
   * <code>string payed = 10;</code>
   */
  com.google.protobuf.ByteString
      getPayedBytes();

  /**
   * <code>.google.protobuf.DoubleValue pay_stock = 11;</code>
   */
  boolean hasPayStock();
  /**
   * <code>.google.protobuf.DoubleValue pay_stock = 11;</code>
   */
  com.google.protobuf.DoubleValue getPayStock();
  /**
   * <code>.google.protobuf.DoubleValue pay_stock = 11;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getPayStockOrBuilder();

  /**
   * <code>string period_shortname = 12;</code>
   */
  java.lang.String getPeriodShortname();
  /**
   * <code>string period_shortname = 12;</code>
   */
  com.google.protobuf.ByteString
      getPeriodShortnameBytes();

  /**
   * <code>string perioddate = 13;</code>
   */
  java.lang.String getPerioddate();
  /**
   * <code>string perioddate = 13;</code>
   */
  com.google.protobuf.ByteString
      getPerioddateBytes();

  /**
   * <code>string protocol_date = 14;</code>
   */
  java.lang.String getProtocolDate();
  /**
   * <code>string protocol_date = 14;</code>
   */
  com.google.protobuf.ByteString
      getProtocolDateBytes();

  /**
   * <code>string report_pay_date = 15;</code>
   */
  java.lang.String getReportPayDate();
  /**
   * <code>string report_pay_date = 15;</code>
   */
  com.google.protobuf.ByteString
      getReportPayDateBytes();

  /**
   * <code>.google.protobuf.DoubleValue sum_dividval = 16;</code>
   */
  boolean hasSumDividval();
  /**
   * <code>.google.protobuf.DoubleValue sum_dividval = 16;</code>
   */
  com.google.protobuf.DoubleValue getSumDividval();
  /**
   * <code>.google.protobuf.DoubleValue sum_dividval = 16;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getSumDividvalOrBuilder();

  /**
   * <code>int64 update_date = 17;</code>
   */
  long getUpdateDate();
}
