// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

/**
 * Protobuf type {@code ShareDividendResponse}
 */
public  final class ShareDividendResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ShareDividendResponse)
    ShareDividendResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShareDividendResponse.newBuilder() to construct.
  private ShareDividendResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShareDividendResponse() {
    reqId_ = "";
    shareDividends_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShareDividendResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShareDividendResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reqId_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              shareDividends_ = new java.util.ArrayList<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend>();
              mutable_bitField0_ |= 0x00000001;
            }
            shareDividends_.add(
                input.readMessage(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        shareDividends_ = java.util.Collections.unmodifiableList(shareDividends_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_ShareDividendResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_ShareDividendResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse.Builder.class);
  }

  public static final int REQID_FIELD_NUMBER = 1;
  private volatile java.lang.Object reqId_;
  /**
   * <code>string reqId = 1;</code>
   */
  public java.lang.String getReqId() {
    java.lang.Object ref = reqId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reqId_ = s;
      return s;
    }
  }
  /**
   * <code>string reqId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReqIdBytes() {
    java.lang.Object ref = reqId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHAREDIVIDENDS_FIELD_NUMBER = 2;
  private java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend> shareDividends_;
  /**
   * <code>repeated .ShareDividend shareDividends = 2;</code>
   */
  public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend> getShareDividendsList() {
    return shareDividends_;
  }
  /**
   * <code>repeated .ShareDividend shareDividends = 2;</code>
   */
  public java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendOrBuilder> 
      getShareDividendsOrBuilderList() {
    return shareDividends_;
  }
  /**
   * <code>repeated .ShareDividend shareDividends = 2;</code>
   */
  public int getShareDividendsCount() {
    return shareDividends_.size();
  }
  /**
   * <code>repeated .ShareDividend shareDividends = 2;</code>
   */
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend getShareDividends(int index) {
    return shareDividends_.get(index);
  }
  /**
   * <code>repeated .ShareDividend shareDividends = 2;</code>
   */
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendOrBuilder getShareDividendsOrBuilder(
      int index) {
    return shareDividends_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReqIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqId_);
    }
    for (int i = 0; i < shareDividends_.size(); i++) {
      output.writeMessage(2, shareDividends_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReqIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqId_);
    }
    for (int i = 0; i < shareDividends_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, shareDividends_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse)) {
      return super.equals(obj);
    }
    com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse other = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse) obj;

    if (!getReqId()
        .equals(other.getReqId())) return false;
    if (!getShareDividendsList()
        .equals(other.getShareDividendsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + getReqId().hashCode();
    if (getShareDividendsCount() > 0) {
      hash = (37 * hash) + SHAREDIVIDENDS_FIELD_NUMBER;
      hash = (53 * hash) + getShareDividendsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ShareDividendResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ShareDividendResponse)
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_ShareDividendResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_ShareDividendResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse.class, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse.Builder.class);
    }

    // Construct using com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getShareDividendsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reqId_ = "";

      if (shareDividendsBuilder_ == null) {
        shareDividends_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        shareDividendsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.GrpcService.internal_static_ShareDividendResponse_descriptor;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse getDefaultInstanceForType() {
      return com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse build() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse buildPartial() {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse result = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse(this);
      int from_bitField0_ = bitField0_;
      result.reqId_ = reqId_;
      if (shareDividendsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          shareDividends_ = java.util.Collections.unmodifiableList(shareDividends_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.shareDividends_ = shareDividends_;
      } else {
        result.shareDividends_ = shareDividendsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse) {
        return mergeFrom((com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse other) {
      if (other == com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse.getDefaultInstance()) return this;
      if (!other.getReqId().isEmpty()) {
        reqId_ = other.reqId_;
        onChanged();
      }
      if (shareDividendsBuilder_ == null) {
        if (!other.shareDividends_.isEmpty()) {
          if (shareDividends_.isEmpty()) {
            shareDividends_ = other.shareDividends_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureShareDividendsIsMutable();
            shareDividends_.addAll(other.shareDividends_);
          }
          onChanged();
        }
      } else {
        if (!other.shareDividends_.isEmpty()) {
          if (shareDividendsBuilder_.isEmpty()) {
            shareDividendsBuilder_.dispose();
            shareDividendsBuilder_ = null;
            shareDividends_ = other.shareDividends_;
            bitField0_ = (bitField0_ & ~0x00000001);
            shareDividendsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getShareDividendsFieldBuilder() : null;
          } else {
            shareDividendsBuilder_.addAllMessages(other.shareDividends_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object reqId_ = "";
    /**
     * <code>string reqId = 1;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder setReqId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder clearReqId() {
      
      reqId_ = getDefaultInstance().getReqId();
      onChanged();
      return this;
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public Builder setReqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reqId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend> shareDividends_ =
      java.util.Collections.emptyList();
    private void ensureShareDividendsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        shareDividends_ = new java.util.ArrayList<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend>(shareDividends_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendOrBuilder> shareDividendsBuilder_;

    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend> getShareDividendsList() {
      if (shareDividendsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(shareDividends_);
      } else {
        return shareDividendsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public int getShareDividendsCount() {
      if (shareDividendsBuilder_ == null) {
        return shareDividends_.size();
      } else {
        return shareDividendsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend getShareDividends(int index) {
      if (shareDividendsBuilder_ == null) {
        return shareDividends_.get(index);
      } else {
        return shareDividendsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder setShareDividends(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend value) {
      if (shareDividendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShareDividendsIsMutable();
        shareDividends_.set(index, value);
        onChanged();
      } else {
        shareDividendsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder setShareDividends(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder builderForValue) {
      if (shareDividendsBuilder_ == null) {
        ensureShareDividendsIsMutable();
        shareDividends_.set(index, builderForValue.build());
        onChanged();
      } else {
        shareDividendsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder addShareDividends(com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend value) {
      if (shareDividendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShareDividendsIsMutable();
        shareDividends_.add(value);
        onChanged();
      } else {
        shareDividendsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder addShareDividends(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend value) {
      if (shareDividendsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShareDividendsIsMutable();
        shareDividends_.add(index, value);
        onChanged();
      } else {
        shareDividendsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder addShareDividends(
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder builderForValue) {
      if (shareDividendsBuilder_ == null) {
        ensureShareDividendsIsMutable();
        shareDividends_.add(builderForValue.build());
        onChanged();
      } else {
        shareDividendsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder addShareDividends(
        int index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder builderForValue) {
      if (shareDividendsBuilder_ == null) {
        ensureShareDividendsIsMutable();
        shareDividends_.add(index, builderForValue.build());
        onChanged();
      } else {
        shareDividendsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder addAllShareDividends(
        java.lang.Iterable<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend> values) {
      if (shareDividendsBuilder_ == null) {
        ensureShareDividendsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, shareDividends_);
        onChanged();
      } else {
        shareDividendsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder clearShareDividends() {
      if (shareDividendsBuilder_ == null) {
        shareDividends_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        shareDividendsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public Builder removeShareDividends(int index) {
      if (shareDividendsBuilder_ == null) {
        ensureShareDividendsIsMutable();
        shareDividends_.remove(index);
        onChanged();
      } else {
        shareDividendsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder getShareDividendsBuilder(
        int index) {
      return getShareDividendsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendOrBuilder getShareDividendsOrBuilder(
        int index) {
      if (shareDividendsBuilder_ == null) {
        return shareDividends_.get(index);  } else {
        return shareDividendsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public java.util.List<? extends com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendOrBuilder> 
         getShareDividendsOrBuilderList() {
      if (shareDividendsBuilder_ != null) {
        return shareDividendsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(shareDividends_);
      }
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder addShareDividendsBuilder() {
      return getShareDividendsFieldBuilder().addBuilder(
          com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.getDefaultInstance());
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder addShareDividendsBuilder(
        int index) {
      return getShareDividendsFieldBuilder().addBuilder(
          index, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.getDefaultInstance());
    }
    /**
     * <code>repeated .ShareDividend shareDividends = 2;</code>
     */
    public java.util.List<com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder> 
         getShareDividendsBuilderList() {
      return getShareDividendsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendOrBuilder> 
        getShareDividendsFieldBuilder() {
      if (shareDividendsBuilder_ == null) {
        shareDividendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividend.Builder, com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendOrBuilder>(
                shareDividends_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        shareDividends_ = null;
      }
      return shareDividendsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ShareDividendResponse)
  }

  // @@protoc_insertion_point(class_scope:ShareDividendResponse)
  private static final com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse();
  }

  public static com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShareDividendResponse>
      PARSER = new com.google.protobuf.AbstractParser<ShareDividendResponse>() {
    @java.lang.Override
    public ShareDividendResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShareDividendResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShareDividendResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShareDividendResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bcs.bm.catalog_of_instruments_rudata.client.grpc.ShareDividendResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

