// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface StringKeysOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StringKeys)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; keys = 1;</code>
   */
  int getKeysCount();
  /**
   * <code>map&lt;string, string&gt; keys = 1;</code>
   */
  boolean containsKeys(
      java.lang.String key);
  /**
   * Use {@link #getKeysMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getKeys();
  /**
   * <code>map&lt;string, string&gt; keys = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getKeysMap();
  /**
   * <code>map&lt;string, string&gt; keys = 1;</code>
   */

  java.lang.String getKeysOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; keys = 1;</code>
   */

  java.lang.String getKeysOrThrow(
      java.lang.String key);
}
