// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcService.proto

package com.bcs.bm.catalog_of_instruments_rudata.client.grpc;

public interface SubscribeEmitentsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscribeEmitentsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 update_date = 1;</code>
   */
  long getUpdateDate();
}
